In [1]:
pd.read_csv("D:\APL_Logistics_Project\01_Raw_Data\APL_Logistics.csv", encoding="latin1")

NameError: name 'pd' is not defined

In [3]:
import pandas as pd
pd.read_csv(r"D:\APL_Logistics_Project\01_Raw_Data\APL_Logistics.csv", encoding="latin1")

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,TRANSFER,6,4,-107.96,161.87,Late delivery,1,76,Women's Clothing,Caguas,...,1,215.82,161.87,-107.96,Southeast Asia,Java Occidental,PROCESSING,Summer dresses,215.82,Standard Class
180515,DEBIT,2,4,-126.56,172.66,Advance shipping,0,76,Women's Clothing,Plainfield,...,1,215.82,172.66,-126.56,Southeast Asia,Java Occidental,COMPLETE,Summer dresses,215.82,Standard Class
180516,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,...,1,327.75,314.64,91.25,Southeast Asia,Java Occidental,COMPLETE,Smart watch,327.75,Standard Class
180517,PAYMENT,4,4,1.53,10.91,Shipping on time,0,74,Toys,Berwyn,...,1,11.54,10.91,1.53,Southeast Asia,Java Occidental,PENDING_PAYMENT,Toys,11.54,Standard Class
180518,CASH,1,0,9.79,34.98,Late delivery,1,75,Video Games,Miami,...,1,39.75,34.98,9.79,Oceania,Queensland,CLOSED,Fighting video games,39.75,Same Day

In [4]:
import pandas as pd

# ==========================================
# DAY 1 - STEP 1: DATASET INSPECTION
# ==========================================

# Load dataset
file_path = r"D:\APL_Logistics_Project\01_Raw_Data\APL_Logistics.csv"

df = pd.read_csv(
    file_path,
    encoding="latin1"
)

# Basic information
print("========== DATASET OVERVIEW ==========")

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\n========== COLUMN NAMES ==========")
print(df.columns.tolist())

print("\n========== FIRST 5 ROWS ==========")
display(df.head())

print("\n========== DATA TYPES ==========")
print(df.dtypes)

print("\n========== DATASET INFORMATION ==========")
df.info()

========== DATASET OVERVIEW ==========
Number of Rows: 180519
Number of Columns: 40

========== COLUMN NAMES ==========
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Product Name', 'Product Price', 'Shipping Mode']

========== FIRST 5 ROWS ==========

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

========== DATA TYPES ==========
Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Product Name                      object
Product Price                    float64
Shipping Mode                     object
dtype: object

========== DATASET INFORMATION ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Fname                 180519 non-null  object
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  object
 14  Customer Segment               180519 non-null  object
 15  Customer State                 180519 non-null  object
 16  Customer Street                180519 non-null  object
 17  Customer Zipcode               180516 non-null  float64
 18  Department Id                  180519 non-null  int64
 19  Department Name                180519 non-null  object
 20  Latitude                       180519 non-null  float64
 21  Longitude                      180519 non-null  float64
 22  Market                         180519 non-null  object
 23  Order City                     180519 non-null  object
 24  Order Country                  180519 non-null  object
 25  Order Customer Id              180519 non-null  int64
 26  Order Item Discount            180519 non-null  float64
 27  Order Item Discount Rate       180519 non-null  float64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  object
 35  Order State                    180519 non-null  object
 36  Order Status                   180519 non-null  object
 37  Product Name                   180519 non-null  object
 38  Product Price                  180519 non-null  float64
 39  Shipping Mode                  180519 non-null  object
dtypes: float64(13), int64(8), object(19)
memory usage: 55.1+ MB

In [5]:
# ==========================================
# MISSING VALUES
# ==========================================

print("\n========== MISSING VALUES ==========")

missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0].sort_values(
    ascending=False
)

print(missing_values)

========== MISSING VALUES ==========
Customer Lname      8
Customer Zipcode    3
dtype: int64

In [6]:
# ==========================================
# DAY 1 - STEP 2.2
# DUPLICATE ANALYSIS
# ==========================================

duplicate_count = df.duplicated().sum()

print("Total Duplicate Rows:", duplicate_count)

if duplicate_count == 0:
    print("✅ No duplicate rows found.")
else:
    print("⚠️ Duplicate rows found.")

Total Duplicate Rows: 0
✅ No duplicate rows found.

In [7]:
# ==========================================
# DAY 1 - STEP 2.3
# SHIPPING TIME VALIDATION
# ==========================================

shipping_cols = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)"
]

print("========== SHIPPING SUMMARY ==========")

display(
    df[shipping_cols].describe()
)

print("\nUnique Actual Shipping Days:")
print(
    sorted(
        df["Days for shipping (real)"].unique()
    )
)

print("\nUnique Scheduled Shipping Days:")
print(
    sorted(
        df["Days for shipment (scheduled)"].unique()
    )
)

========== SHIPPING SUMMARY ==========

       Days for shipping (real)  Days for shipment (scheduled)
count             180519.000000                  180519.000000
mean                   3.497654                       2.931847
std                    1.623722                       1.374449
min                    0.000000                       0.000000
25%                    2.000000                       2.000000
50%                    3.000000                       4.000000
75%                    5.000000                       4.000000
max                    6.000000                       4.000000

Unique Actual Shipping Days:
[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]

Unique Scheduled Shipping Days:
[np.int64(0), np.int64(1), np.int64(2), np.int64(4)]

In [8]:
# ==========================================
# DAY 1 - STEP 2.4
# DELIVERY STATUS VALIDATION
# ==========================================

print("========== DELIVERY STATUS ==========")

delivery_status = df["Delivery Status"].value_counts()

display(delivery_status)

print("\nUnique Delivery Status Values:")
print(df["Delivery Status"].unique())

========== DELIVERY STATUS ==========

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Unique Delivery Status Values:
['Late delivery' 'Shipping on time' 'Advance shipping' 'Shipping canceled']

In [9]:
# ==========================================
# DAY 1 - STEP 2.5
# LATE DELIVERY RISK VALIDATION
# ==========================================

print("========== LATE DELIVERY RISK ==========")

risk_summary = df["Late_delivery_risk"].value_counts()

display(risk_summary)

print("\nUnique Late Delivery Risk Values:")
print(
    sorted(df["Late_delivery_risk"].unique())
)

print("\nData Type:")
print(df["Late_delivery_risk"].dtype)

========== LATE DELIVERY RISK ==========

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Unique Late Delivery Risk Values:
[np.int64(0), np.int64(1)]

Data Type:
int64

In [10]:
# ==========================================
# DAY 1 - STEP 3
# HANDLE MISSING VALUES
# ==========================================

# Fill missing customer last names
df["Customer Lname"] = df["Customer Lname"].fillna("Unknown")

print("Missing Customer Lname:",
      df["Customer Lname"].isnull().sum())

print("Missing Customer Zipcode:",
      df["Customer Zipcode"].isnull().sum())

Missing Customer Lname: 0
Missing Customer Zipcode: 3

In [11]:
# ==========================================
# DAY 1 - STEP 4
# CATEGORICAL CONSISTENCY CHECK
# ==========================================

categorical_cols = [
    "Type",
    "Delivery Status",
    "Category Name",
    "Customer Country",
    "Customer Segment",
    "Department Name",
    "Market",
    "Order Country",
    "Order Region",
    "Order Status",
    "Shipping Mode"
]

for col in categorical_cols:
    print(f"\n========== {col} ==========")
    print("Unique values:", df[col].nunique())
    print(df[col].unique()[:20])

========== Type ==========
Unique values: 4
['DEBIT' 'PAYMENT' 'TRANSFER' 'CASH']

========== Delivery Status ==========
Unique values: 4
['Late delivery' 'Shipping on time' 'Advance shipping' 'Shipping canceled']

========== Category Name ==========
Unique values: 50
['Cardio Equipment' 'Shop By Sport' 'Water Sports' "Women's Apparel"
 'Camping & Hiking' 'Indoor/Outdoor Games' 'Fishing' 'Cleats'
 'Electronics' "Men's Footwear" 'Accessories' 'Fitness Accessories'
 'Trade-In' 'Baseball & Softball' 'Golf Gloves' "Men's Golf Clubs"
 'Golf Balls' 'Hockey' 'Golf Shoes' 'Boxing & MMA']

========== Customer Country ==========
Unique values: 2
['EE. UU.' 'Puerto Rico']

========== Customer Segment ==========
Unique values: 3
['Consumer' 'Home Office' 'Corporate']

========== Department Name ==========
Unique values: 11
['Footwear' 'Golf' 'Fan Shop' 'Apparel' 'Outdoors' 'Fitness' 'Book Shop'
 'Discs Shop' 'Technology' 'Health and Beauty ' 'Pet Shop']

========== Market ==========
Unique values: 5
['Pacific Asia' 'LATAM' 'USCA' 'Europe' 'Africa']

========== Order Country ==========
Unique values: 164
['India' 'Honduras' 'Estados Unidos' 'Italia' 'Alemania' 'Australia'
 'Brasil' 'México' 'Turquía' 'Nigeria' 'Cuba'
 'República Democrática del Congo' 'Filipinas' 'Reino Unido' 'China'
 'Indonesia' 'República Dominicana' 'Francia' 'Colombia' 'Suecia']

========== Order Region ==========
Unique values: 23
['South Asia' 'Central America' 'East of USA' 'Southern Europe'
 'Western Europe' 'Oceania' 'South America' 'West Asia' 'West Africa'
 'Caribbean' 'US Center ' 'Central Africa' 'Southeast Asia'
 'Northern Europe' 'Eastern Asia' 'South of  USA ' 'Southern Africa'
 'West of USA ' 'Eastern Europe' 'Canada']

========== Order Status ==========
Unique values: 9
['COMPLETE' 'ON_HOLD' 'PENDING_PAYMENT' 'PENDING' 'CLOSED' 'PROCESSING'
 'PAYMENT_REVIEW' 'SUSPECTED_FRAUD' 'CANCELED']

========== Shipping Mode ==========
Unique values: 4
['Standard Class' 'Same Day' 'First Class' 'Second Class']

In [12]:
# ==========================================
# DAY 1 - STEP 4.1
# REMOVE LEADING/TRAILING SPACES
# ==========================================

categorical_cols = [
    "Type",
    "Delivery Status",
    "Category Name",
    "Customer Country",
    "Customer Segment",
    "Department Name",
    "Market",
    "Order Country",
    "Order Region",
    "Order Status",
    "Shipping Mode"
]

for col in categorical_cols:
    df[col] = df[col].str.strip()

print("✅ Leading/trailing spaces removed from categorical columns.")

✅ Leading/trailing spaces removed from categorical columns.

In [13]:
print("========== Department Name ==========")
print(df["Department Name"].unique())

print("\n========== Order Region ==========")
print(df["Order Region"].unique())

========== Department Name ==========
['Footwear' 'Golf' 'Fan Shop' 'Apparel' 'Outdoors' 'Fitness' 'Book Shop'
 'Discs Shop' 'Technology' 'Health and Beauty' 'Pet Shop']

========== Order Region ==========
['South Asia' 'Central America' 'East of USA' 'Southern Europe'
 'Western Europe' 'Oceania' 'South America' 'West Asia' 'West Africa'
 'Caribbean' 'US Center' 'Central Africa' 'Southeast Asia'
 'Northern Europe' 'Eastern Asia' 'South of  USA' 'Southern Africa'
 'West of USA' 'Eastern Europe' 'Canada' 'East Africa' 'North Africa'
 'Central Asia']

In [14]:
# ==========================================
# DAY 1 - STEP 4.2
# NORMALIZE MULTIPLE SPACES
# ==========================================

for col in categorical_cols:
    df[col] = df[col].str.replace(r"\s+", " ", regex=True).str.strip()

print("✅ Multiple spaces normalized.")

✅ Multiple spaces normalized.

In [15]:
print(df["Order Region"].unique())

['South Asia' 'Central America' 'East of USA' 'Southern Europe'
 'Western Europe' 'Oceania' 'South America' 'West Asia' 'West Africa'
 'Caribbean' 'US Center' 'Central Africa' 'Southeast Asia'
 'Northern Europe' 'Eastern Asia' 'South of USA' 'Southern Africa'
 'West of USA' 'Eastern Europe' 'Canada' 'East Africa' 'North Africa'
 'Central Asia']

In [16]:
# ==========================================
# DAY 1 - STEP 5
# NUMERIC DATA VALIDATION
# ==========================================

numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

numeric_summary = pd.DataFrame({
    "Min": df[numeric_cols].min(),
    "Max": df[numeric_cols].max(),
    "Missing": df[numeric_cols].isnull().sum()
})

display(numeric_summary)

                                       Min           Max  Missing
Days for shipping (real)          0.000000      6.000000        0
Days for shipment (scheduled)     0.000000      4.000000        0
Benefit per order             -4274.980000    911.800000        0
Sales per customer                7.490000   1939.990000        0
Late_delivery_risk                0.000000      1.000000        0
Category Id                       2.000000     76.000000        0
Customer Id                       1.000000  20757.000000        0
Customer Zipcode                603.000000  99205.000000        3
Department Id                     2.000000     12.000000        0
Latitude                        -33.937553     48.781933        0
Longitude                      -158.025986    115.263077        0
Order Customer Id                 1.000000  20757.000000        0
Order Item Discount               0.000000    500.000000        0
Order Item Discount Rate          0.000000      0.250000        0
Order Item Product Price          9.990000   1999.990000        0
Order Item Profit Ratio          -2.750000      0.500000        0
Order Item Quantity               1.000000      5.000000        0
Sales                             9.990000   1999.990000        0
Order Item Total                  7.490000   1939.990000        0
Order Profit Per Order        -4274.980000    911.800000        0
Product Price                     9.990000   1999.990000        0

In [17]:
# ==========================================
# DAY 1 - FINAL CLEANING VERIFICATION
# ==========================================

print("========== FINAL DATASET CHECK ==========")

print("Dataset Shape:", df.shape)

print("\nTotal Duplicate Rows:", df.duplicated().sum())

print("\nMissing Values:")
display(
    df.isnull().sum()[df.isnull().sum() > 0]
)

print("\nCustomer Lname Missing:",
      df["Customer Lname"].isnull().sum())

print("\nCustomer Zipcode Missing:",
      df["Customer Zipcode"].isnull().sum())

========== FINAL DATASET CHECK ==========
Dataset Shape: (180519, 40)

Total Duplicate Rows: 0

Missing Values:

Customer Zipcode    3
dtype: int64

Customer Lname Missing: 0

Customer Zipcode Missing: 3

In [18]:
# ==========================================
# DAY 1 - SAVE CLEANED DATASET
# ==========================================

cleaned_path = r"D:\APL_Logistics_Project\03_Cleaned_Data\APL_Logistics_Cleaned.csv"

df.to_csv(
    cleaned_path,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Cleaned dataset saved successfully!")
print("File:", cleaned_path)

✅ Cleaned dataset saved successfully!
File: D:\APL_Logistics_Project\03_Cleaned_Data\APL_Logistics_Cleaned.csv

In [19]:
# ==========================================
# VERIFY SAVED DATASET
# ==========================================

df_check = pd.read_csv(
    cleaned_path,
    encoding="utf-8-sig"
)

print("Saved Dataset Shape:", df_check.shape)
print("Saved Dataset Columns:", len(df_check.columns))

Saved Dataset Shape: (180519, 40)
Saved Dataset Columns: 40

In [20]:
# ==========================================
# DAY 2 - STEP 1
# LOAD CLEANED DATASET
# ==========================================

import pandas as pd

cleaned_path = r"D:\APL_Logistics_Project\03_Cleaned_Data\APL_Logistics_Cleaned.csv"

df = pd.read_csv(
    cleaned_path,
    encoding="utf-8-sig"
)

print("✅ Cleaned dataset loaded successfully!")
print("Dataset Shape:", df.shape)

✅ Cleaned dataset loaded successfully!
Dataset Shape: (180519, 40)

In [21]:
# ==========================================
# DAY 2 - STEP 2
# CREATE DELAY GAP
# ==========================================

df["Delay Gap"] = (
    df["Days for shipping (real)"]
    - df["Days for shipment (scheduled)"]
)

print("✅ Delay Gap feature created!")

print("\nDelay Gap Summary:")
display(
    df["Delay Gap"].describe()
)

print("\nUnique Delay Gap Values:")
print(
    sorted(df["Delay Gap"].unique())
)

✅ Delay Gap feature created!

Delay Gap Summary:

count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: Delay Gap, dtype: float64

Unique Delay Gap Values:
[np.int64(-2), np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]

In [22]:
# ==========================================
# DAY 2 - STEP 3
# DELIVERY PERFORMANCE CLASSIFICATION
# ==========================================

df["Delivery Performance"] = "On-Time"

# Canceled shipments
df.loc[
    df["Delivery Status"] == "Shipping canceled",
    "Delivery Performance"
] = "Canceled"

# Early shipments
df.loc[
    (df["Delay Gap"] < 0) &
    (df["Delivery Status"] != "Shipping canceled"),
    "Delivery Performance"
] = "Early"

# Delayed shipments
df.loc[
    (df["Delay Gap"] > 0) &
    (df["Delivery Status"] != "Shipping canceled"),
    "Delivery Performance"
] = "Delayed"

# Check results
print("✅ Delivery Performance classification created!")

print("\nDelivery Performance Counts:")
print(df["Delivery Performance"].value_counts())

print("\nDelivery Performance Percentages:")
print(
    df["Delivery Performance"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

✅ Delivery Performance classification created!

Delivery Performance Counts:
Delivery Performance
Delayed     98977
Early       41592
On-Time     32196
Canceled     7754
Name: count, dtype: int64

Delivery Performance Percentages:
Delivery Performance
Delayed     54.83
Early       23.04
On-Time     17.84
Canceled     4.30
Name: proportion, dtype: float64

In [23]:
# ==========================================
# DAY 2 - STEP 4
# VALIDATE DELIVERY PERFORMANCE
# ==========================================

validation_table = pd.crosstab(
    df["Delivery Status"],
    df["Delivery Performance"]
)

print("✅ Validation table created!")

display(validation_table)

✅ Validation table created!

Delivery Performance  Canceled  Delayed  Early  On-Time
Delivery Status
Advance shipping             0        0  41592        0
Late delivery                0    98977      0        0
Shipping canceled         7754        0      0        0
Shipping on time             0        0      0    32196

In [24]:
print("\nOriginal Delivery Status:")
print(df["Delivery Status"].value_counts())

print("\nEngineered Delivery Performance:")
print(df["Delivery Performance"].value_counts())

Original Delivery Status:
Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

Engineered Delivery Performance:
Delivery Performance
Delayed     98977
Early       41592
On-Time     32196
Canceled     7754
Name: count, dtype: int64

In [25]:
# ==========================================
# DAY 2 - STEP 5
# OVERALL DELIVERY PERFORMANCE KPIs
# ==========================================

# Exclude canceled shipments for delivery-performance KPIs
non_canceled = df[
    df["Delivery Performance"] != "Canceled"
]

# Total non-canceled shipments
total_non_canceled = len(non_canceled)

# Shipment counts
delayed_count = (
    non_canceled["Delivery Performance"] == "Delayed"
).sum()

on_time_count = (
    non_canceled["Delivery Performance"] == "On-Time"
).sum()

early_count = (
    non_canceled["Delivery Performance"] == "Early"
).sum()

canceled_count = (
    df["Delivery Performance"] == "Canceled"
).sum()

# KPI calculations
on_time_rate = (
    on_time_count / total_non_canceled
) * 100

early_rate = (
    early_count / total_non_canceled
) * 100

delay_rate = (
    delayed_count / total_non_canceled
) * 100

cancellation_rate = (
    canceled_count / len(df)
) * 100

# Average delay across non-canceled shipments
average_delay_gap = (
    non_canceled["Delay Gap"].mean()
)

# Average delay only among delayed shipments
average_delay_delayed = (
    non_canceled.loc[
        non_canceled["Delivery Performance"] == "Delayed",
        "Delay Gap"
    ].mean()
)

print("==========================================")
print("OVERALL DELIVERY PERFORMANCE KPIs")
print("==========================================")

print(f"Total Shipments          : {len(df):,}")
print(f"Non-Canceled Shipments   : {total_non_canceled:,}")
print(f"Delayed Shipments        : {delayed_count:,}")
print(f"On-Time Shipments        : {on_time_count:,}")
print(f"Early Shipments          : {early_count:,}")
print(f"Canceled Shipments       : {canceled_count:,}")

print("\n--- KPI RESULTS ---")

print(f"On-Time Delivery Rate    : {on_time_rate:.2f}%")
print(f"Delay Rate               : {delay_rate:.2f}%")
print(f"Early Delivery Rate      : {early_rate:.2f}%")
print(f"Cancellation Rate        : {cancellation_rate:.2f}%")

print(f"\nAverage Delay Gap        : {average_delay_gap:.2f} days")
print(
    f"Avg Delay When Delayed   : "
    f"{average_delay_delayed:.2f} days"
)

==========================================
OVERALL DELIVERY PERFORMANCE KPIs
==========================================
Total Shipments          : 180,519
Non-Canceled Shipments   : 172,765
Delayed Shipments        : 98,977
On-Time Shipments        : 32,196
Early Shipments          : 41,592
Canceled Shipments       : 7,754

--- KPI RESULTS ---
On-Time Delivery Rate    : 18.64%
Delay Rate               : 57.29%
Early Delivery Rate      : 24.07%
Cancellation Rate        : 4.30%

Average Delay Gap        : 0.57 days
Avg Delay When Delayed   : 1.62 days

In [26]:
# ==========================================
# DAY 2 - STEP 6
# LATE DELIVERY RISK ANALYSIS
# ==========================================

print("==========================================")
print("LATE DELIVERY RISK ANALYSIS")
print("==========================================")

# Risk distribution
risk_counts = df["Late_delivery_risk"].value_counts()

print("\nLate Delivery Risk Counts:")
print(risk_counts)

print("\nLate Delivery Risk Percentages:")
print(
    df["Late_delivery_risk"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

# Compare risk flag with actual delivery performance
risk_vs_performance = pd.crosstab(
    df["Late_delivery_risk"],
    df["Delivery Performance"]
)

print("\nRisk Flag vs Delivery Performance:")
display(risk_vs_performance)

# Compare risk flag with original Delivery Status
risk_vs_status = pd.crosstab(
    df["Late_delivery_risk"],
    df["Delivery Status"]
)

print("\nRisk Flag vs Original Delivery Status:")
display(risk_vs_status)

==========================================
LATE DELIVERY RISK ANALYSIS
==========================================

Late Delivery Risk Counts:
Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

Late Delivery Risk Percentages:
Late_delivery_risk
1    54.83
0    45.17
Name: proportion, dtype: float64

Risk Flag vs Delivery Performance:

Delivery Performance  Canceled  Delayed  Early  On-Time
Late_delivery_risk
0                         7754        0  41592    32196
1                            0    98977      0        0

Risk Flag vs Original Delivery Status:

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Late_delivery_risk,,,,
0,41592,0,7754,32196
1,0,98977,0,0

In [27]:
# ==========================================
# DAY 2 - STEP 7
# CREATE FINAL ANALYSIS DATASET
# ==========================================

analysis_df = df.copy()

print("==========================================")
print("FINAL ANALYSIS DATASET")
print("==========================================")

print("Shape:", analysis_df.shape)

print("\nNew Engineered Columns:")
print([
    "Delay Gap",
    "Delivery Performance"
])

print("\nMissing Values:")
print(
    analysis_df[
        ["Delay Gap", "Delivery Performance"]
    ].isnull().sum()
)

print("\nDuplicate Rows:")
print(analysis_df.duplicated().sum())

==========================================
FINAL ANALYSIS DATASET
==========================================
Shape: (180519, 42)

New Engineered Columns:
['Delay Gap', 'Delivery Performance']

Missing Values:
Delay Gap               0
Delivery Performance    0
dtype: int64

Duplicate Rows:
0

In [29]:
# ==========================================
# SAVE DAY 2 ANALYSIS DATASET
# ==========================================

analysis_path = (
    r"D:\APL_Logistics_Project"
    r"\04_Analysis"
    r"\APL_Logistics_Analysis.csv"
)

analysis_df.to_csv(
    analysis_path,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Analysis dataset saved successfully!")
print("Saved at:", analysis_path)

✅ Analysis dataset saved successfully!
Saved at: D:\APL_Logistics_Project\04_Analysis\APL_Logistics_Analysis.csv

In [30]:
# ==========================================
# DAY 3 - STEP 1
# SHIPPING MODE DISTRIBUTION
# ==========================================

print("==========================================")
print("SHIPPING MODE ANALYSIS")
print("==========================================")

shipping_mode_counts = (
    analysis_df["Shipping Mode"]
    .value_counts()
)

print("\nShipping Mode Counts:")
print(shipping_mode_counts)

print("\nShipping Mode Percentages:")
print(
    analysis_df["Shipping Mode"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

==========================================
SHIPPING MODE ANALYSIS
==========================================

Shipping Mode Counts:
Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

Shipping Mode Percentages:
Shipping Mode
Standard Class    59.69
Second Class      19.51
First Class       15.41
Same Day           5.39
Name: proportion, dtype: float64

In [31]:
# ==========================================
# DAY 3 - STEP 2
# SHIPPING MODE DELAY PERFORMANCE
# ==========================================

shipping_mode_analysis = (
    analysis_df
    .groupby("Shipping Mode")
    .agg(
        Total_Shipments=("Shipping Mode", "size"),
        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),
        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),
        Early_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Early").sum()
        ),
        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        ),
        Average_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Calculate delay rate
shipping_mode_analysis["Delay_Rate_%"] = (
    shipping_mode_analysis["Delayed_Shipments"]
    / shipping_mode_analysis["Total_Shipments"]
    * 100
)

# Calculate on-time rate
shipping_mode_analysis["On_Time_Rate_%"] = (
    shipping_mode_analysis["On_Time_Shipments"]
    /
    (
        shipping_mode_analysis["Total_Shipments"]
        - shipping_mode_analysis["Canceled_Shipments"]
    )
    * 100
)

# Sort by highest delay rate
shipping_mode_analysis = (
    shipping_mode_analysis
    .sort_values("Delay_Rate_%", ascending=False)
)

print("==========================================")
print("SHIPPING MODE DELAY PERFORMANCE")
print("==========================================")

display(
    shipping_mode_analysis.round(2)
)

==========================================
SHIPPING MODE DELAY PERFORMANCE
==========================================

,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Delay_Rate_%,On_Time_Rate_%
0,First Class,27814,26513,0,0,1301,1.00,95.32,0.00
2,Second Class,35216,26987,6819,0,1410,1.99,76.63,20.17
1,Same Day,9737,4454,4839,0,444,0.48,45.74,52.07
3,Standard Class,107752,41023,20538,41592,4599,-0.00,38.07,19.91

In [32]:
# ==========================================
# DAY 3 - STEP 3
# AVERAGE DELAY WHEN ACTUALLY DELAYED
# ==========================================

shipping_mode_delay = (
    analysis_df[
        analysis_df["Delivery Performance"] == "Delayed"
    ]
    .groupby("Shipping Mode")
    .agg(
        Delayed_Shipments=("Delay Gap", "count"),
        Average_Delay_When_Delayed=("Delay Gap", "mean"),
        Maximum_Delay=("Delay Gap", "max")
    )
    .reset_index()
)

shipping_mode_delay = (
    shipping_mode_delay
    .sort_values(
        "Average_Delay_When_Delayed",
        ascending=False
    )
)

print("==========================================")
print("AVERAGE DELAY WHEN ACTUALLY DELAYED")
print("==========================================")

display(
    shipping_mode_delay.round(2)
)

==========================================
AVERAGE DELAY WHEN ACTUALLY DELAYED
==========================================

,Shipping Mode,Delayed_Shipments,Average_Delay_When_Delayed,Maximum_Delay
2,Second Class,26987,2.50,4
3,Standard Class,41023,1.51,2
0,First Class,26513,1.00,1
1,Same Day,4454,1.00,1

In [33]:
# ==========================================
# DAY 3 - STEP 4
# SHIPPING MODE EFFICIENCY INDEX
# ==========================================

shipping_efficiency = (
    analysis_df
    .groupby("Shipping Mode")
    .agg(
        Total_Shipments=("Shipping Mode", "size"),
        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),
        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),
        Early_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Early").sum()
        ),
        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        )
    )
    .reset_index()
)

# Non-canceled shipments
shipping_efficiency["Non_Canceled"] = (
    shipping_efficiency["Total_Shipments"]
    - shipping_efficiency["Canceled_Shipments"]
)

# Delay rate
shipping_efficiency["Delay_Rate_%"] = (
    shipping_efficiency["Delayed_Shipments"]
    / shipping_efficiency["Non_Canceled"]
    * 100
)

# On-time rate
shipping_efficiency["On_Time_Rate_%"] = (
    shipping_efficiency["On_Time_Shipments"]
    / shipping_efficiency["Non_Canceled"]
    * 100
)

# Efficiency Index
shipping_efficiency["Efficiency_Index"] = (
    shipping_efficiency["On_Time_Rate_%"]
    - shipping_efficiency["Delay_Rate_%"]
)

# Cancellation rate
shipping_efficiency["Cancellation_Rate_%"] = (
    shipping_efficiency["Canceled_Shipments"]
    / shipping_efficiency["Total_Shipments"]
    * 100
)

# Sort best to worst
shipping_efficiency = (
    shipping_efficiency
    .sort_values("Efficiency_Index", ascending=False)
)

print("==========================================")
print("SHIPPING MODE EFFICIENCY INDEX")
print("==========================================")

display(
    shipping_efficiency.round(2)
)

==========================================
SHIPPING MODE EFFICIENCY INDEX
==========================================

,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Efficiency_Index,Cancellation_Rate_%
1,Same Day,9737,4454,4839,0,444,9293,47.93,52.07,4.14,4.56
3,Standard Class,107752,41023,20538,41592,4599,103153,39.77,19.91,-19.86,4.27
2,Second Class,35216,26987,6819,0,1410,33806,79.83,20.17,-59.66,4.00
0,First Class,27814,26513,0,0,1301,26513,100.00,0.00,-100.00,4.68

In [34]:
# ==========================================
# DAY 3 - STEP 5
# REGIONAL DELAY ANALYSIS
# ==========================================

regional_analysis = (
    analysis_df
    .groupby("Order Region")
    .agg(
        Total_Shipments=("Order Region", "size"),
        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),
        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),
        Early_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Early").sum()
        ),
        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        ),
        Average_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
regional_analysis["Non_Canceled"] = (
    regional_analysis["Total_Shipments"]
    - regional_analysis["Canceled_Shipments"]
)

# Delay rate
regional_analysis["Delay_Rate_%"] = (
    regional_analysis["Delayed_Shipments"]
    / regional_analysis["Non_Canceled"]
    * 100
)

# On-time rate
regional_analysis["On_Time_Rate_%"] = (
    regional_analysis["On_Time_Shipments"]
    / regional_analysis["Non_Canceled"]
    * 100
)

# Regional Delay Index
regional_analysis["Regional_Delay_Index"] = (
    regional_analysis["Delay_Rate_%"]
)

# Sort by highest delay rate
regional_analysis = (
    regional_analysis
    .sort_values(
        "Delay_Rate_%",
        ascending=False
    )
)

print("==========================================")
print("REGIONAL DELAY ANALYSIS")
print("==========================================")

display(
    regional_analysis.round(2)
)

==========================================
REGIONAL DELAY ANALYSIS
==========================================

,Order Region,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Regional_Delay_Index
2,Central Africa,1677,972,290,354,61,0.64,1616,60.15,17.95,60.15
22,Western Europe,27109,15140,4589,6138,1242,0.60,25867,58.53,17.74,58.53
14,South of USA,4045,2256,672,927,190,0.58,3855,58.52,17.43,58.52
13,South Asia,7731,4350,1340,1765,276,0.60,7455,58.35,17.97,58.35
5,East Africa,1852,1036,346,399,71,0.57,1781,58.17,19.43,58.17
6,East of USA,6915,3849,1208,1560,298,0.58,6617,58.17,18.26,58.17
15,Southeast Asia,9539,5297,1631,2208,403,0.56,9136,57.98,17.85,57.98
20,West Asia,6009,3322,1114,1310,263,0.57,5746,57.81,19.39,57.81
8,Eastern Europe,3920,2182,724,879,135,0.58,3785,57.65,19.13,57.65
18,US Center,5887,3252,1174,1227,234,0.59,5653,57.53,20.77,57.53
12,South America,14935,8111,2597,3476,751,0.56,14184,57.18,18.31,57.18
3,Central America,28341,15518,5090,6566,1167,0.56,27174,57.11,18.73,57.11
9,North Africa,3232,1762,564,760,146,0.55,3086,57.10,18.28,57.10
17,Southern Europe,9431,5129,1655,2246,401,0.52,9030,56.80,18.33,56.80
21,West of USA,7993,4313,1447,1835,398,0.56,7595,56.79,19.05,56.79
7,Eastern Asia,7280,3955,1264,1754,307,0.57,6973,56.72,18.13,56.72
4,Central Asia,553,306,124,112,11,0.65,542,56.46,22.88,56.46
11,Oceania,10148,5482,1927,2324,415,0.56,9733,56.32,19.80,56.32
10,Northern Europe,9792,5292,1775,2341,384,0.55,9408,56.25,18.87,56.25
16,Southern Africa,1157,617,200,283,57,0.48,1100,56.09,18.18,56.09
1,Caribbean,8318,4415,1539,1997,367,0.55,7951,55.53,19.36,55.53
19,West Africa,3696,1953,769,849,125,0.55,3571,54.69,21.53,54.69
0,Canada,959,468,157,282,52,0.39,907,51.60,17.31,51.60

In [35]:
# ==========================================
# DAY 3 - STEP 6
# REGIONAL ANALYSIS VALIDATION
# ==========================================

canada_check = analysis_df[
    analysis_df["Order Region"] == "Canada"
]

print("Canada Delivery Performance:")
display(
    canada_check["Delivery Performance"]
    .value_counts()
)

print("\nCanada Delay Gap:")
display(
    canada_check["Delay Gap"]
    .value_counts()
    .sort_index()
)

print("\nCanada Late Delivery Risk:")
display(
    canada_check["Late_delivery_risk"]
    .value_counts()
)

print("\nMissing values in Canada:")
display(
    canada_check[
        ["Delivery Performance", "Delay Gap", "Late_delivery_risk"]
    ].isna().sum()
)

Canada Delivery Performance:

Delivery Performance
Delayed     468
Early       282
On-Time     157
Canceled     52
Name: count, dtype: int64

Canada Delay Gap:

Delay Gap
-2    137
-1    154
 0    170
 1    300
 2    127
 3     35
 4     36
Name: count, dtype: int64

Canada Late Delivery Risk:

Late_delivery_risk
0    491
1    468
Name: count, dtype: int64

Missing values in Canada:

Delivery Performance    0
Delay Gap               0
Late_delivery_risk      0
dtype: int64

In [36]:
# ==========================================
# DAY 3 - STEP 7
# MARKET DELAY ANALYSIS
# ==========================================

market_analysis = (
    analysis_df
    .groupby("Market")
    .agg(
        Total_Shipments=("Market", "size"),

        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),

        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),

        Early_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Early").sum()
        ),

        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        ),

        Average_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
market_analysis["Non_Canceled"] = (
    market_analysis["Total_Shipments"]
    - market_analysis["Canceled_Shipments"]
)

# Delay rate
market_analysis["Delay_Rate_%"] = (
    market_analysis["Delayed_Shipments"]
    / market_analysis["Non_Canceled"]
    * 100
)

# On-time rate
market_analysis["On_Time_Rate_%"] = (
    market_analysis["On_Time_Shipments"]
    / market_analysis["Non_Canceled"]
    * 100
)

# Cancellation rate
market_analysis["Cancellation_Rate_%"] = (
    market_analysis["Canceled_Shipments"]
    / market_analysis["Total_Shipments"]
    * 100
)

# Market Delay Index
market_analysis["Market_Delay_Index"] = (
    market_analysis["Delay_Rate_%"]
)

# Sort by delay rate
market_analysis = (
    market_analysis
    .sort_values(
        "Delay_Rate_%",
        ascending=False
    )
)

print("==========================================")
print("MARKET DELAY ANALYSIS")
print("==========================================")

display(
    market_analysis.round(2)
)

==========================================
MARKET DELAY ANALYSIS
==========================================

,Market,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Cancellation_Rate_%,Market_Delay_Index
1,Europe,50252,27743,8743,11604,2162,0.57,48090,57.69,18.18,4.30,57.69
4,USCA,25799,14138,4658,5831,1172,0.57,24627,57.41,18.91,4.54,57.41
3,Pacific Asia,41260,22712,7400,9473,1675,0.57,39585,57.38,18.69,4.06,57.38
2,LATAM,51594,28044,9226,12039,2285,0.56,49309,56.87,18.71,4.43,56.87
0,Africa,11614,6340,2169,2645,460,0.56,11154,56.84,19.45,3.96,56.84

In [37]:
# ==========================================
# DAY 3 - STEP 8
# MARKET × SHIPPING MODE ANALYSIS
# ==========================================

market_mode_analysis = (
    analysis_df
    .groupby(["Market", "Shipping Mode"])
    .agg(
        Total_Shipments=("Shipping Mode", "size"),

        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),

        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),

        Early_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Early").sum()
        ),

        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        ),

        Average_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
market_mode_analysis["Non_Canceled"] = (
    market_mode_analysis["Total_Shipments"]
    - market_mode_analysis["Canceled_Shipments"]
)

# Delay rate
market_mode_analysis["Delay_Rate_%"] = (
    market_mode_analysis["Delayed_Shipments"]
    / market_mode_analysis["Non_Canceled"]
    * 100
)

# On-time rate
market_mode_analysis["On_Time_Rate_%"] = (
    market_mode_analysis["On_Time_Shipments"]
    / market_mode_analysis["Non_Canceled"]
    * 100
)

# Efficiency index
market_mode_analysis["Efficiency_Index"] = (
    market_mode_analysis["On_Time_Rate_%"]
    - market_mode_analysis["Delay_Rate_%"]
)

# Sort by market and highest delay
market_mode_analysis = (
    market_mode_analysis
    .sort_values(
        ["Market", "Delay_Rate_%"],
        ascending=[True, False]
    )
)

print("==========================================")
print("MARKET × SHIPPING MODE ANALYSIS")
print("==========================================")

display(
    market_mode_analysis.round(2)
)

==========================================
MARKET × SHIPPING MODE ANALYSIS
==========================================

,Market,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Efficiency_Index
0,Africa,First Class,1727,1675,0,0,52,1.00,1675,100.00,0.00,-100.00
2,Africa,Second Class,2164,1675,416,0,73,1.98,2091,80.11,19.89,-60.21
1,Africa,Same Day,668,294,340,0,34,0.47,634,46.37,53.63,7.26
3,Africa,Standard Class,7055,2696,1413,2645,301,0.02,6754,39.92,20.92,-19.00
4,Europe,First Class,7892,7562,0,0,330,1.00,7562,100.00,0.00,-100.00
6,Europe,Second Class,9861,7596,1874,0,391,2.00,9470,80.21,19.79,-60.42
5,Europe,Same Day,2759,1281,1343,0,135,0.49,2624,48.82,51.18,2.36
7,Europe,Standard Class,29740,11304,5526,11604,1306,-0.01,28434,39.76,19.43,-20.32
8,LATAM,First Class,7886,7471,0,0,415,1.00,7471,100.00,0.00,-100.00
10,LATAM,Second Class,9939,7510,1988,0,441,1.98,9498,79.07,20.93,-58.14
9,LATAM,Same Day,2650,1273,1255,0,122,0.51,2528,50.36,49.64,-0.71
11,LATAM,Standard Class,31119,11790,5983,12039,1307,-0.01,29812,39.55,20.07,-19.48
12,Pacific Asia,First Class,6301,5991,0,0,310,1.00,5991,100.00,0.00,-100.00
14,Pacific Asia,Second Class,8147,6293,1536,0,318,2.00,7829,80.38,19.62,-60.76
13,Pacific Asia,Same Day,2226,969,1166,0,91,0.45,2135,45.39,54.61,9.23
15,Pacific Asia,Standard Class,24586,9459,4698,9473,956,-0.00,23630,40.03,19.88,-20.15
16,USCA,First Class,4008,3814,0,0,194,1.00,3814,100.00,0.00,-100.00
18,USCA,Second Class,5105,3913,1005,0,187,1.98,4918,79.56,20.44,-59.13
17,USCA,Same Day,1434,637,735,0,62,0.45,1372,46.43,53.57,7.14
19,USCA,Standard Class,15252,5774,2918,5831,729,-0.00,14523,39.76,20.09,-19.67

In [38]:
# ==========================================
# DAY 3 - STEP 9
# REGION × SHIPPING MODE ANALYSIS
# ==========================================

region_mode_analysis = (
    analysis_df
    .groupby(["Order Region", "Shipping Mode"])
    .agg(
        Total_Shipments=("Shipping Mode", "size"),

        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),

        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),

        Early_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Early").sum()
        ),

        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        ),

        Average_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
region_mode_analysis["Non_Canceled"] = (
    region_mode_analysis["Total_Shipments"]
    - region_mode_analysis["Canceled_Shipments"]
)

# Delay rate
region_mode_analysis["Delay_Rate_%"] = (
    region_mode_analysis["Delayed_Shipments"]
    / region_mode_analysis["Non_Canceled"]
    * 100
)

# On-time rate
region_mode_analysis["On_Time_Rate_%"] = (
    region_mode_analysis["On_Time_Shipments"]
    / region_mode_analysis["Non_Canceled"]
    * 100
)

# Efficiency index
region_mode_analysis["Efficiency_Index"] = (
    region_mode_analysis["On_Time_Rate_%"]
    - region_mode_analysis["Delay_Rate_%"]
)

# Sort by highest delay rate
region_mode_analysis = (
    region_mode_analysis
    .sort_values(
        "Delay_Rate_%",
        ascending=False
    )
)

print("==========================================")
print("REGION × SHIPPING MODE ANALYSIS")
print("==========================================")

display(
    region_mode_analysis.round(2)
)

==========================================
REGION × SHIPPING MODE ANALYSIS
==========================================

,Order Region,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Efficiency_Index
0,Canada,First Class,184,170,0,0,14,1.00,170,100.00,0.00,-100.00
72,US Center,First Class,986,951,0,0,35,1.00,951,100.00,0.00,-100.00
40,Northern Europe,First Class,1418,1361,0,0,57,1.00,1361,100.00,0.00,-100.00
32,Eastern Europe,First Class,658,632,0,0,26,1.00,632,100.00,0.00,-100.00
44,Oceania,First Class,1366,1270,0,0,96,1.00,1270,100.00,0.00,-100.00
...,...,...,...,...,...,...,...,...,...,...,...,...
33,Eastern Europe,Same Day,178,64,112,0,2,0.36,176,36.36,63.64,27.27
9,Central Africa,Same Day,79,24,55,0,0,0.30,79,30.38,69.62,39.24
3,Canada,Standard Class,576,166,106,282,22,-0.27,554,29.96,19.13,-10.83
1,Canada,Same Day,33,7,22,0,4,0.33,29,24.14,75.86,51.72
17,Central Asia,Same Day,64,13,51,0,0,0.20,64,20.31,79.69,59.38

In [39]:
# ==========================================
# DAY 3 - STEP 10
# TOP REGIONAL SHIPPING-MODE RISKS
# ==========================================

# Top 10 highest delay-rate combinations
top_risks = (
    region_mode_analysis[
        region_mode_analysis["Non_Canceled"] > 0
    ]
    .sort_values(
        ["Delay_Rate_%", "Non_Canceled"],
        ascending=[False, False]
    )
    .head(10)
)

print("==========================================")
print("TOP 10 REGIONAL SHIPPING-MODE RISKS")
print("==========================================")

display(
    top_risks[
        [
            "Order Region",
            "Shipping Mode",
            "Total_Shipments",
            "Delayed_Shipments",
            "On_Time_Shipments",
            "Early_Shipments",
            "Canceled_Shipments",
            "Non_Canceled",
            "Delay_Rate_%",
            "On_Time_Rate_%",
            "Efficiency_Index"
        ]
    ].round(2)
)


# ==========================================
# TOP 10 BEST COMBINATIONS
# ==========================================

top_performers = (
    region_mode_analysis[
        region_mode_analysis["Non_Canceled"] > 0
    ]
    .sort_values(
        ["Efficiency_Index", "Non_Canceled"],
        ascending=[False, False]
    )
    .head(10)
)

print("\n==========================================")
print("TOP 10 BEST REGIONAL SHIPPING-MODE COMBINATIONS")
print("==========================================")

display(
    top_performers[
        [
            "Order Region",
            "Shipping Mode",
            "Total_Shipments",
            "Delayed_Shipments",
            "On_Time_Shipments",
            "Early_Shipments",
            "Canceled_Shipments",
            "Non_Canceled",
            "Delay_Rate_%",
            "On_Time_Rate_%",
            "Efficiency_Index"
        ]
    ].round(2)
)

==========================================
TOP 10 REGIONAL SHIPPING-MODE RISKS
==========================================

,Order Region,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Efficiency_Index
12,Central America,First Class,4382,4185,0,0,197,4185,100.0,0.0,-100.0
88,Western Europe,First Class,4312,4107,0,0,205,4107,100.0,0.0,-100.0
48,South America,First Class,2311,2154,0,0,157,2154,100.0,0.0,-100.0
60,Southeast Asia,First Class,1552,1482,0,0,70,1482,100.0,0.0,-100.0
68,Southern Europe,First Class,1504,1462,0,0,42,1462,100.0,0.0,-100.0
40,Northern Europe,First Class,1418,1361,0,0,57,1361,100.0,0.0,-100.0
44,Oceania,First Class,1366,1270,0,0,96,1270,100.0,0.0,-100.0
52,South Asia,First Class,1283,1240,0,0,43,1240,100.0,0.0,-100.0
4,Caribbean,First Class,1193,1132,0,0,61,1132,100.0,0.0,-100.0
84,West of USA,First Class,1149,1072,0,0,77,1072,100.0,0.0,-100.0

==========================================
TOP 10 BEST REGIONAL SHIPPING-MODE COMBINATIONS
==========================================

,Order Region,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Efficiency_Index
17,Central Asia,Same Day,64,13,51,0,0,64,20.31,79.69,59.38
1,Canada,Same Day,33,7,22,0,4,29,24.14,75.86,51.72
9,Central Africa,Same Day,79,24,55,0,0,79,30.38,69.62,39.24
33,Eastern Europe,Same Day,178,64,112,0,2,176,36.36,63.64,27.27
77,West Africa,Same Day,223,79,133,0,11,212,37.26,62.74,25.47
73,US Center,Same Day,323,125,193,0,5,318,39.31,60.69,21.38
41,Northern Europe,Same Day,517,206,296,0,15,502,41.04,58.96,17.93
45,Oceania,Same Day,647,263,348,0,36,611,43.04,56.96,13.91
21,East Africa,Same Day,98,41,54,0,3,95,43.16,56.84,13.68
61,Southeast Asia,Same Day,451,184,240,0,27,424,43.40,56.60,13.21

In [40]:
# ==========================================
# DAY 3 - STEP 11
# SAVE ANALYSIS TABLES
# ==========================================

analysis_path = r"D:\APL_Logistics_Project\04_Analysis"

# Create folder if it doesn't exist
import os
os.makedirs(analysis_path, exist_ok=True)


# ------------------------------------------
# 1. Shipping Mode Analysis
# ------------------------------------------

shipping_efficiency.to_csv(
    os.path.join(
        analysis_path,
        "Shipping_Mode_Analysis.csv"
    ),
    index=False
)


# ------------------------------------------
# 2. Regional Analysis
# ------------------------------------------

regional_analysis.to_csv(
    os.path.join(
        analysis_path,
        "Regional_Analysis.csv"
    ),
    index=False
)


# ------------------------------------------
# 3. Market Analysis
# ------------------------------------------

market_analysis.to_csv(
    os.path.join(
        analysis_path,
        "Market_Analysis.csv"
    ),
    index=False
)


# ------------------------------------------
# 4. Market × Shipping Mode
# ------------------------------------------

market_mode_analysis.to_csv(
    os.path.join(
        analysis_path,
        "Market_Shipping_Mode_Analysis.csv"
    ),
    index=False
)


# ------------------------------------------
# 5. Region × Shipping Mode
# ------------------------------------------

region_mode_analysis.to_csv(
    os.path.join(
        analysis_path,
        "Region_Shipping_Mode_Analysis.csv"
    ),
    index=False
)


# ------------------------------------------
# 6. Top Regional Risks
# ------------------------------------------

top_risks.to_csv(
    os.path.join(
        analysis_path,
        "Top_Regional_Shipping_Risks.csv"
    ),
    index=False
)


# ------------------------------------------
# 7. Top Regional Performers
# ------------------------------------------

top_performers.to_csv(
    os.path.join(
        analysis_path,
        "Top_Regional_Shipping_Performers.csv"
    ),
    index=False
)


print("==========================================")
print("DAY 3 ANALYSIS TABLES SAVED SUCCESSFULLY")
print("==========================================")

print("\nSaved files:")

for file in os.listdir(analysis_path):
    if file.endswith(".csv"):
        print("✓", file)

==========================================
DAY 3 ANALYSIS TABLES SAVED SUCCESSFULLY
==========================================

Saved files:
✓ APL_Logistics_Analysis.csv
✓ Market_Analysis.csv
✓ Market_Shipping_Mode_Analysis.csv
✓ Regional_Analysis.csv
✓ Region_Shipping_Mode_Analysis.csv
✓ Shipping_Mode_Analysis.csv
✓ Top_Regional_Shipping_Performers.csv
✓ Top_Regional_Shipping_Risks.csv

In [41]:
# ==========================================
# DAY 4 - STEP 1
# CUSTOMER SEGMENT ANALYSIS
# ==========================================

# Check customer segments
customer_segments = df["Customer Segment"].value_counts()

print("Customer Segment Distribution:")
print(customer_segments)

print("\nNumber of Customer Segments:", df["Customer Segment"].nunique())

Customer Segment Distribution:
Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

Number of Customer Segments: 3

In [42]:
# ==========================================
# DAY 4 - STEP 2
# CUSTOMER SEGMENT DELIVERY PERFORMANCE
# ==========================================

segment_analysis = (
    df.groupby("Customer Segment")
      .agg(
          Total=("Customer Segment", "size"),
          Delayed=("Delivery Performance", lambda x: (x == "Delayed").sum()),
          On_Time=("Delivery Performance", lambda x: (x == "On-Time").sum()),
          Early=("Delivery Performance", lambda x: (x == "Early").sum()),
          Canceled=("Delivery Performance", lambda x: (x == "Canceled").sum()),
          Avg_Delay_Gap=("Delay Gap", "mean")
      )
      .reset_index()
)

# Non-canceled shipments
segment_analysis["Non_Canceled"] = (
    segment_analysis["Total"] -
    segment_analysis["Canceled"]
)

# Delay rate among non-canceled shipments
segment_analysis["Delay_Rate_%"] = (
    segment_analysis["Delayed"] /
    segment_analysis["Non_Canceled"] * 100
)

# On-time rate among non-canceled shipments
segment_analysis["On_Time_Rate_%"] = (
    segment_analysis["On_Time"] /
    segment_analysis["Non_Canceled"] * 100
)

# Cancellation rate
segment_analysis["Cancellation_Rate_%"] = (
    segment_analysis["Canceled"] /
    segment_analysis["Total"] * 100
)

# Round percentages
segment_analysis["Delay_Rate_%"] = segment_analysis["Delay_Rate_%"].round(2)
segment_analysis["On_Time_Rate_%"] = segment_analysis["On_Time_Rate_%"].round(2)
segment_analysis["Cancellation_Rate_%"] = segment_analysis["Cancellation_Rate_%"].round(2)
segment_analysis["Avg_Delay_Gap"] = segment_analysis["Avg_Delay_Gap"].round(2)

print("Customer Segment Delivery Performance:")
display(segment_analysis)

Customer Segment Delivery Performance:

,Customer Segment,Total,Delayed,On_Time,Early,Canceled,Avg_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Cancellation_Rate_%
0,Consumer,93504,51248,16784,21388,4084,0.56,89420,57.31,18.77,4.37
1,Corporate,54789,29982,9690,12856,2261,0.56,52528,57.08,18.45,4.13
2,Home Office,32226,17747,5722,7348,1409,0.58,30817,57.59,18.57,4.37

In [43]:
# ==========================================
# DAY 4 - STEP 3
# CUSTOMER SEGMENT × SHIPPING MODE
# ==========================================

segment_mode_analysis = (
    df.groupby(
        ["Customer Segment", "Shipping Mode"]
    )
    .agg(
        Total=("Shipping Mode", "size"),
        Delayed=("Delivery Performance",
                 lambda x: (x == "Delayed").sum()),
        On_Time=("Delivery Performance",
                 lambda x: (x == "On-Time").sum()),
        Early=("Delivery Performance",
               lambda x: (x == "Early").sum()),
        Canceled=("Delivery Performance",
                  lambda x: (x == "Canceled").sum()),
        Avg_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
segment_mode_analysis["Non_Canceled"] = (
    segment_mode_analysis["Total"]
    - segment_mode_analysis["Canceled"]
)

# Delay rate
segment_mode_analysis["Delay_Rate_%"] = (
    segment_mode_analysis["Delayed"]
    / segment_mode_analysis["Non_Canceled"]
    * 100
)

# On-time rate
segment_mode_analysis["On_Time_Rate_%"] = (
    segment_mode_analysis["On_Time"]
    / segment_mode_analysis["Non_Canceled"]
    * 100
)

# Cancellation rate
segment_mode_analysis["Cancellation_Rate_%"] = (
    segment_mode_analysis["Canceled"]
    / segment_mode_analysis["Total"]
    * 100
)

# Efficiency Index
segment_mode_analysis["Efficiency_Index"] = (
    segment_mode_analysis["On_Time_Rate_%"]
    - segment_mode_analysis["Delay_Rate_%"]
)

# Round values
for col in [
    "Avg_Delay_Gap",
    "Delay_Rate_%",
    "On_Time_Rate_%",
    "Cancellation_Rate_%",
    "Efficiency_Index"
]:
    segment_mode_analysis[col] = (
        segment_mode_analysis[col].round(2)
    )

print("Customer Segment × Shipping Mode:")
display(segment_mode_analysis)

Customer Segment × Shipping Mode:

,Customer Segment,Shipping Mode,Total,Delayed,On_Time,Early,Canceled,Avg_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Cancellation_Rate_%,Efficiency_Index
0,Consumer,First Class,14407,13708,0,0,699,1.00,13708,100.00,0.00,4.85,-100.00
1,Consumer,Same Day,5148,2393,2530,0,225,0.49,4923,48.61,51.39,4.37,2.78
2,Consumer,Second Class,17997,13699,3525,0,773,1.98,17224,79.53,20.47,4.30,-59.07
3,Consumer,Standard Class,55952,21448,10729,21388,2387,0.00,53565,40.04,20.03,4.27,-20.01
4,Corporate,First Class,8282,7904,0,0,378,1.00,7904,100.00,0.00,4.56,-100.00
5,Corporate,Same Day,2975,1374,1450,0,151,0.48,2824,48.65,51.35,5.08,2.69
6,Corporate,Second Class,10950,8530,2028,0,392,2.00,10558,80.79,19.21,3.58,-61.58
7,Corporate,Standard Class,32582,12174,6212,12856,1340,-0.03,31242,38.97,19.88,4.11,-19.08
8,Home Office,First Class,5125,4901,0,0,224,1.00,4901,100.00,0.00,4.37,-100.00
9,Home Office,Same Day,1614,687,859,0,68,0.44,1546,44.44,55.56,4.21,11.13
10,Home Office,Second Class,6269,4758,1266,0,245,2.00,6024,78.98,21.02,3.91,-57.97
11,Home Office,Standard Class,19218,7401,3597,7348,872,0.01,18346,40.34,19.61,4.54,-20.73

In [44]:
# ==========================================
# DAY 4 - STEP 4
# RISK DIAGNOSTICS
# DELAY GAP DISTRIBUTION
# ==========================================

print("Delay Gap Distribution:")
print(
    df["Delay Gap"]
    .value_counts()
    .sort_index()
)

print("\nPercentage Distribution:")

delay_gap_distribution = (
    df["Delay Gap"]
    .value_counts(normalize=True)
    .sort_index()
    * 100
)

print(delay_gap_distribution.round(2))

Delay Gap Distribution:
Delay Gap
-2    21666
-1    21700
 0    33753
 1    60647
 2    28718
 3     7052
 4     6983
Name: count, dtype: int64

Percentage Distribution:
Delay Gap
-2    12.00
-1    12.02
 0    18.70
 1    33.60
 2    15.91
 3     3.91
 4     3.87
Name: proportion, dtype: float64

In [45]:
# ==========================================
# DAY 4 - STEP 5
# DELAYED vs NON-DELAYED COMPARISON
# ==========================================

comparison_columns = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Delay Gap",
    "Sales",
    "Order Item Quantity",
    "Order Item Discount Rate",
    "Order Item Profit Ratio"
]

# Create delayed/non-delayed groups
delay_comparison = (
    df.groupby("Delivery Performance")[comparison_columns]
      .mean()
      .round(2)
)

print("Average Metrics by Delivery Performance:")
display(delay_comparison)

Average Metrics by Delivery Performance:

,Days for shipping (real),Days for shipment (scheduled),Delay Gap,Sales,Order Item Quantity,Order Item Discount Rate,Order Item Profit Ratio
Delivery Performance,,,,,,,
Canceled,3.48,2.90,0.57,202.52,2.13,0.1,0.12
Delayed,4.09,2.47,1.62,203.34,2.13,0.1,0.12
Early,2.50,4.00,-1.50,204.80,2.13,0.1,0.12
On-Time,2.98,2.98,0.00,204.06,2.12,0.1,0.12

In [46]:
# ==========================================
# DAY 4 - STEP 6
# LATE DELIVERY RISK BY CUSTOMER SEGMENT
# ==========================================

risk_by_segment = (
    df.groupby("Customer Segment")
      .agg(
          Total_Shipments=("Late_delivery_risk", "size"),
          Risk_1=("Late_delivery_risk", lambda x: (x == 1).sum()),
          Risk_0=("Late_delivery_risk", lambda x: (x == 0).sum())
      )
      .reset_index()
)

# Risk percentage
risk_by_segment["Risk_Rate_%"] = (
    risk_by_segment["Risk_1"]
    / risk_by_segment["Total_Shipments"]
    * 100
)

risk_by_segment["Risk_Rate_%"] = (
    risk_by_segment["Risk_Rate_%"].round(2)
)

print("Late Delivery Risk by Customer Segment:")
display(risk_by_segment)

Late Delivery Risk by Customer Segment:

  Customer Segment  Total_Shipments  Risk_1  Risk_0  Risk_Rate_%
0         Consumer            93504   51248   42256        54.81
1        Corporate            54789   29982   24807        54.72
2      Home Office            32226   17747   14479        55.07

In [47]:
# ==========================================
# DAY 4 - STEP 7
# REGIONAL RISK DIAGNOSTICS
# ==========================================

regional_risk = (
    df.groupby("Order Region")
      .agg(
          Total_Shipments=("Late_delivery_risk", "size"),
          Risk_1=("Late_delivery_risk", lambda x: (x == 1).sum()),
          Risk_0=("Late_delivery_risk", lambda x: (x == 0).sum()),
          Avg_Delay_Gap=("Delay Gap", "mean")
      )
      .reset_index()
)

# Risk rate
regional_risk["Risk_Rate_%"] = (
    regional_risk["Risk_1"]
    / regional_risk["Total_Shipments"]
    * 100
)

# Round values
regional_risk["Risk_Rate_%"] = (
    regional_risk["Risk_Rate_%"].round(2)
)

regional_risk["Avg_Delay_Gap"] = (
    regional_risk["Avg_Delay_Gap"].round(2)
)

# Sort from highest risk to lowest
regional_risk = regional_risk.sort_values(
    "Risk_Rate_%",
    ascending=False
).reset_index(drop=True)

print("Top 10 Regions by Late Delivery Risk:")
display(regional_risk.head(10))

Top 10 Regions by Late Delivery Risk:

     Order Region  Total_Shipments  Risk_1  Risk_0  Avg_Delay_Gap  Risk_Rate_%
0  Central Africa             1677     972     705           0.64        57.96
1      South Asia             7731    4350    3381           0.60        56.27
2     East Africa             1852    1036     816           0.57        55.94
3  Western Europe            27109   15140   11969           0.60        55.85
4    South of USA             4045    2256    1789           0.58        55.77
5     East of USA             6915    3849    3066           0.58        55.66
6  Eastern Europe             3920    2182    1738           0.58        55.66
7  Southeast Asia             9539    5297    4242           0.56        55.53
8    Central Asia              553     306     247           0.65        55.33
9       West Asia             6009    3322    2687           0.57        55.28

In [48]:
# ==========================================
# DAY 4 - STEP 8
# REGIONAL RISK PRIORITY
# ==========================================

# Calculate median thresholds
volume_threshold = regional_risk["Total_Shipments"].median()
risk_threshold = regional_risk["Risk_Rate_%"].median()

print("Median Shipment Volume:", volume_threshold)
print("Median Risk Rate:", round(risk_threshold, 2), "%")


# Create priority classification
regional_risk["Risk_Priority"] = "Lower Priority"

regional_risk.loc[
    (regional_risk["Risk_Rate_%"] >= risk_threshold) &
    (regional_risk["Total_Shipments"] >= volume_threshold),
    "Risk_Priority"
] = "High Risk + High Volume"

regional_risk.loc[
    (regional_risk["Risk_Rate_%"] >= risk_threshold) &
    (regional_risk["Total_Shipments"] < volume_threshold),
    "Risk_Priority"
] = "High Risk + Low Volume"

regional_risk.loc[
    (regional_risk["Risk_Rate_%"] < risk_threshold) &
    (regional_risk["Total_Shipments"] >= volume_threshold),
    "Risk_Priority"
] = "Lower Risk + High Volume"


# Display results
priority_columns = [
    "Order Region",
    "Total_Shipments",
    "Risk_1",
    "Risk_Rate_%",
    "Avg_Delay_Gap",
    "Risk_Priority"
]

regional_priority = regional_risk[
    priority_columns
].sort_values(
    ["Risk_Priority", "Risk_Rate_%"],
    ascending=[True, False]
)

print("\nRegional Risk Priority:")
display(regional_priority)

Median Shipment Volume: 6915.0
Median Risk Rate: 54.75 %

Regional Risk Priority:

,Order Region,Total_Shipments,Risk_1,Risk_Rate_%,Avg_Delay_Gap,Risk_Priority
1,South Asia,7731,4350,56.27,0.60,High Risk + High Volume
3,Western Europe,27109,15140,55.85,0.60,High Risk + High Volume
5,East of USA,6915,3849,55.66,0.58,High Risk + High Volume
7,Southeast Asia,9539,5297,55.53,0.56,High Risk + High Volume
11,Central America,28341,15518,54.75,0.56,High Risk + High Volume
0,Central Africa,1677,972,57.96,0.64,High Risk + Low Volume
2,East Africa,1852,1036,55.94,0.57,High Risk + Low Volume
4,South of USA,4045,2256,55.77,0.58,High Risk + Low Volume
6,Eastern Europe,3920,2182,55.66,0.58,High Risk + Low Volume
8,Central Asia,553,306,55.33,0.65,High Risk + Low Volume
9,West Asia,6009,3322,55.28,0.57,High Risk + Low Volume
10,US Center,5887,3252,55.24,0.59,High Risk + Low Volume
12,North Africa,3232,1762,54.52,0.55,Lower Priority
19,Southern Africa,1157,617,53.33,0.48,Lower Priority
21,West Africa,3696,1953,52.84,0.55,Lower Priority
22,Canada,959,468,48.80,0.39,Lower Priority
13,Southern Europe,9431,5129,54.38,0.52,Lower Risk + High Volume
14,Eastern Asia,7280,3955,54.33,0.57,Lower Risk + High Volume
15,South America,14935,8111,54.31,0.56,Lower Risk + High Volume
16,Northern Europe,9792,5292,54.04,0.55,Lower Risk + High Volume
17,Oceania,10148,5482,54.02,0.56,Lower Risk + High Volume
18,West of USA,7993,4313,53.96,0.56,Lower Risk + High Volume
20,Caribbean,8318,4415,53.08,0.55,Lower Risk + High Volume

In [49]:
# ==========================================
# DAY 4 - STEP 9
# RISK CONCENTRATION BY REGION
# ==========================================

risk_concentration = (
    regional_risk[
        [
            "Order Region",
            "Total_Shipments",
            "Risk_1",
            "Risk_Rate_%",
            "Avg_Delay_Gap"
        ]
    ]
    .copy()
)

# Calculate each region's share of total risk-affected shipments
total_risk_shipments = risk_concentration["Risk_1"].sum()

risk_concentration["Risk_Contribution_%"] = (
    risk_concentration["Risk_1"]
    / total_risk_shipments
    * 100
).round(2)

# Sort by number of risk-affected shipments
risk_concentration = (
    risk_concentration
    .sort_values("Risk_1", ascending=False)
    .reset_index(drop=True)
)

print("Top Regions by Risk-Affected Shipment Volume:")

display(risk_concentration)

Top Regions by Risk-Affected Shipment Volume:

,Order Region,Total_Shipments,Risk_1,Risk_Rate_%,Avg_Delay_Gap,Risk_Contribution_%
0,Central America,28341,15518,54.75,0.56,15.68
1,Western Europe,27109,15140,55.85,0.60,15.30
2,South America,14935,8111,54.31,0.56,8.19
3,Oceania,10148,5482,54.02,0.56,5.54
4,Southeast Asia,9539,5297,55.53,0.56,5.35
5,Northern Europe,9792,5292,54.04,0.55,5.35
6,Southern Europe,9431,5129,54.38,0.52,5.18
7,Caribbean,8318,4415,53.08,0.55,4.46
8,South Asia,7731,4350,56.27,0.60,4.39
9,West of USA,7993,4313,53.96,0.56,4.36
10,Eastern Asia,7280,3955,54.33,0.57,4.00
11,East of USA,6915,3849,55.66,0.58,3.89
12,West Asia,6009,3322,55.28,0.57,3.36
13,US Center,5887,3252,55.24,0.59,3.29
14,South of USA,4045,2256,55.77,0.58,2.28
15,Eastern Europe,3920,2182,55.66,0.58,2.20
16,West Africa,3696,1953,52.84,0.55,1.97
17,North Africa,3232,1762,54.52,0.55,1.78
18,East Africa,1852,1036,55.94,0.57,1.05
19,Central Africa,1677,972,57.96,0.64,0.98
20,Southern Africa,1157,617,53.33,0.48,0.62
21,Canada,959,468,48.80,0.39,0.47
22,Central Asia,553,306,55.33,0.65,0.31

In [50]:
# ==========================================
# DAY 4 - STEP 10
# FINAL KPI SUMMARY
# ==========================================

total_shipments = len(df)

non_canceled = (
    df["Delivery Performance"] != "Canceled"
).sum()

delayed_shipments = (
    df["Delivery Performance"] == "Delayed"
).sum()

on_time_shipments = (
    df["Delivery Performance"] == "On-Time"
).sum()

early_shipments = (
    df["Delivery Performance"] == "Early"
).sum()

canceled_shipments = (
    df["Delivery Performance"] == "Canceled"
).sum()


# Overall KPIs
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Shipments",
        "Delayed Shipments",
        "On-Time Shipments",
        "Early Shipments",
        "Canceled Shipments",
        "Delay Rate %",
        "On-Time Rate %",
        "Early Delivery Rate %",
        "Cancellation Rate %",
        "Average Delay Gap",
        "Average Delay When Delayed",
        "Late Delivery Risk Rate %"
    ],
    
    "Value": [
        total_shipments,
        delayed_shipments,
        on_time_shipments,
        early_shipments,
        canceled_shipments,
        
        round(
            delayed_shipments / non_canceled * 100,
            2
        ),
        
        round(
            on_time_shipments / non_canceled * 100,
            2
        ),
        
        round(
            early_shipments / non_canceled * 100,
            2
        ),
        
        round(
            canceled_shipments / total_shipments * 100,
            2
        ),
        
        round(
            df["Delay Gap"].mean(),
            2
        ),
        
        round(
            df.loc[
                df["Delivery Performance"] == "Delayed",
                "Delay Gap"
            ].mean(),
            2
        ),
        
        round(
            df["Late_delivery_risk"].mean() * 100,
            2
        )
    ]
})


print("FINAL DAY 4 KPI SUMMARY")
display(kpi_summary)

FINAL DAY 4 KPI SUMMARY

                           KPI      Value
0              Total Shipments  180519.00
1            Delayed Shipments   98977.00
2            On-Time Shipments   32196.00
3              Early Shipments   41592.00
4           Canceled Shipments    7754.00
5                 Delay Rate %      57.29
6               On-Time Rate %      18.64
7        Early Delivery Rate %      24.07
8          Cancellation Rate %       4.30
9            Average Delay Gap       0.57
10  Average Delay When Delayed       1.62
11   Late Delivery Risk Rate %      54.83

In [51]:
# ==========================================
# DAY 4 - STEP 11
# SAVE ALL DAY 4 ANALYSIS TABLES
# ==========================================

analysis_path = r"D:\APL_Logistics_Project\04_Analysis"

# 1. Customer Segment Analysis
segment_analysis.to_csv(
    analysis_path + r"\Customer_Segment_Analysis.csv",
    index=False,
    encoding="utf-8-sig"
)

# 2. Customer Segment × Shipping Mode
segment_mode_analysis.to_csv(
    analysis_path + r"\Customer_Segment_Shipping_Mode_Analysis.csv",
    index=False,
    encoding="utf-8-sig"
)

# 3. Regional Risk Diagnostics
regional_risk.to_csv(
    analysis_path + r"\Regional_Risk_Diagnostics.csv",
    index=False,
    encoding="utf-8-sig"
)

# 4. Regional Risk Priority
regional_priority.to_csv(
    analysis_path + r"\Regional_Risk_Priority.csv",
    index=False,
    encoding="utf-8-sig"
)

# 5. Risk Concentration
risk_concentration.to_csv(
    analysis_path + r"\Regional_Risk_Concentration.csv",
    index=False,
    encoding="utf-8-sig"
)

# 6. Final KPI Summary
kpi_summary.to_csv(
    analysis_path + r"\Day_4_KPI_Summary.csv",
    index=False,
    encoding="utf-8-sig"
)

print("==========================================")
print("DAY 4 ANALYSIS TABLES SAVED SUCCESSFULLY")
print("==========================================")

print("\nSaved files:")

print("1. Customer_Segment_Analysis.csv")
print("2. Customer_Segment_Shipping_Mode_Analysis.csv")
print("3. Regional_Risk_Diagnostics.csv")
print("4. Regional_Risk_Priority.csv")
print("5. Regional_Risk_Concentration.csv")
print("6. Day_4_KPI_Summary.csv")

==========================================
DAY 4 ANALYSIS TABLES SAVED SUCCESSFULLY
==========================================

Saved files:
1. Customer_Segment_Analysis.csv
2. Customer_Segment_Shipping_Mode_Analysis.csv
3. Regional_Risk_Diagnostics.csv
4. Regional_Risk_Priority.csv
5. Regional_Risk_Concentration.csv
6. Day_4_KPI_Summary.csv

In [52]:
# ==========================================
# DAY 5 - STEP 1
# SHIPPING MODE DEEP DIVE
# ==========================================

shipping_mode_deep_dive = (
    df.groupby("Shipping Mode")
      .agg(
          Total_Shipments=("Shipping Mode", "size"),
          Delayed_Shipments=(
              "Delivery Performance",
              lambda x: (x == "Delayed").sum()
          ),
          On_Time_Shipments=(
              "Delivery Performance",
              lambda x: (x == "On-Time").sum()
          ),
          Early_Shipments=(
              "Delivery Performance",
              lambda x: (x == "Early").sum()
          ),
          Canceled_Shipments=(
              "Delivery Performance",
              lambda x: (x == "Canceled").sum()
          ),
          Avg_Delay_When_Delayed=(
              "Delay Gap",
              lambda x: x[x > 0].mean()
          ),
          Max_Delay=(
              "Delay Gap",
              "max"
          ),
          Severe_Delays_2Plus=(
              "Delay Gap",
              lambda x: (x >= 2).sum()
          )
      )
      .reset_index()
)

# Non-canceled shipments
shipping_mode_deep_dive["Non_Canceled"] = (
    shipping_mode_deep_dive["Total_Shipments"]
    - shipping_mode_deep_dive["Canceled_Shipments"]
)

# Delay rate
shipping_mode_deep_dive["Delay_Rate_%"] = (
    shipping_mode_deep_dive["Delayed_Shipments"]
    / shipping_mode_deep_dive["Non_Canceled"]
    * 100
)

# On-time rate
shipping_mode_deep_dive["On_Time_Rate_%"] = (
    shipping_mode_deep_dive["On_Time_Shipments"]
    / shipping_mode_deep_dive["Non_Canceled"]
    * 100
)

# Severe delay rate among all shipments
shipping_mode_deep_dive["Severe_Delay_Rate_%"] = (
    shipping_mode_deep_dive["Severe_Delays_2Plus"]
    / shipping_mode_deep_dive["Total_Shipments"]
    * 100
)

# Efficiency Index
shipping_mode_deep_dive["Efficiency_Index"] = (
    shipping_mode_deep_dive["On_Time_Rate_%"]
    - shipping_mode_deep_dive["Delay_Rate_%"]
)

# Round numerical values
numeric_columns = [
    "Avg_Delay_When_Delayed",
    "Delay_Rate_%",
    "On_Time_Rate_%",
    "Severe_Delay_Rate_%",
    "Efficiency_Index"
]

shipping_mode_deep_dive[numeric_columns] = (
    shipping_mode_deep_dive[numeric_columns]
    .round(2)
)

# Sort by delay rate
shipping_mode_deep_dive = (
    shipping_mode_deep_dive
    .sort_values("Delay_Rate_%", ascending=False)
    .reset_index(drop=True)
)

print("==========================================")
print("SHIPPING MODE DEEP DIVE")
print("==========================================")

display(shipping_mode_deep_dive)

==========================================
SHIPPING MODE DEEP DIVE
==========================================

,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Avg_Delay_When_Delayed,Max_Delay,Severe_Delays_2Plus,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Severe_Delay_Rate_%,Efficiency_Index
0,First Class,27814,26513,0,0,1301,1.00,1,0,26513,100.00,0.00,0.00,-100.00
1,Second Class,35216,26987,6819,0,1410,2.50,4,21013,33806,79.83,20.17,59.67,-59.66
2,Same Day,9737,4454,4839,0,444,1.00,1,0,9293,47.93,52.07,0.00,4.14
3,Standard Class,107752,41023,20538,41592,4599,1.51,2,21740,103153,39.77,19.91,20.18,-19.86

In [53]:
# ==========================================
# DAY 5 - STEP 2
# SHIPPING MODE × REGION
# DELAY SEVERITY ANALYSIS
# ==========================================

region_mode_severity = (
    df.groupby(
        ["Order Region", "Shipping Mode"]
    )
    .agg(
        Total_Shipments=("Shipping Mode", "size"),

        Delayed_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Delayed").sum()
        ),

        On_Time_Shipments=(
            "Delivery Performance",
            lambda x: (x == "On-Time").sum()
        ),

        Canceled_Shipments=(
            "Delivery Performance",
            lambda x: (x == "Canceled").sum()
        ),

        Avg_Delay_When_Delayed=(
            "Delay Gap",
            lambda x: x[x > 0].mean()
        ),

        Max_Delay=(
            "Delay Gap",
            "max"
        ),

        Severe_Delays_2Plus=(
            "Delay Gap",
            lambda x: (x >= 2).sum()
        )
    )
    .reset_index()
)

# Non-canceled shipments
region_mode_severity["Non_Canceled"] = (
    region_mode_severity["Total_Shipments"]
    - region_mode_severity["Canceled_Shipments"]
)

# Delay rate
region_mode_severity["Delay_Rate_%"] = (
    region_mode_severity["Delayed_Shipments"]
    / region_mode_severity["Non_Canceled"]
    * 100
)

# On-time rate
region_mode_severity["On_Time_Rate_%"] = (
    region_mode_severity["On_Time_Shipments"]
    / region_mode_severity["Non_Canceled"]
    * 100
)

# Severe delay rate
region_mode_severity["Severe_Delay_Rate_%"] = (
    region_mode_severity["Severe_Delays_2Plus"]
    / region_mode_severity["Total_Shipments"]
    * 100
)

# Round
numeric_columns = [
    "Avg_Delay_When_Delayed",
    "Delay_Rate_%",
    "On_Time_Rate_%",
    "Severe_Delay_Rate_%"
]

region_mode_severity[numeric_columns] = (
    region_mode_severity[numeric_columns]
    .round(2)
)

# Remove combinations with no meaningful shipments
region_mode_severity = (
    region_mode_severity[
        region_mode_severity["Total_Shipments"] > 50
    ]
    .copy()
)

# Sort by severe delay rate
region_mode_severity = (
    region_mode_severity
    .sort_values(
        "Severe_Delay_Rate_%",
        ascending=False
    )
    .reset_index(drop=True)
)

print("==========================================")
print("REGION × SHIPPING MODE SEVERITY")
print("==========================================")

display(
    region_mode_severity.head(20)
)

==========================================
REGION × SHIPPING MODE SEVERITY
==========================================

,Order Region,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Canceled_Shipments,Avg_Delay_When_Delayed,Max_Delay,Severe_Delays_2Plus,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Severe_Delay_Rate_%
0,Central Asia,Second Class,117,101,11,5,2.44,4,82,112,90.18,9.82,70.09
1,Eastern Asia,Second Class,1406,1116,225,65,2.52,4,909,1341,83.22,16.78,64.65
2,South of USA,Second Class,829,673,142,14,2.47,4,521,815,82.58,17.42,62.85
3,South Asia,Second Class,1552,1198,303,51,2.56,4,970,1501,79.81,20.19,62.50
4,Canada,Second Class,166,125,29,12,2.63,4,102,154,81.17,18.83,61.45
5,Central Africa,Second Class,297,241,50,6,2.58,4,182,291,82.82,17.18,61.28
6,Western Europe,Second Class,5438,4236,970,232,2.53,4,3332,5206,81.37,18.63,61.27
7,Central America,Second Class,5481,4111,1139,231,2.50,4,3311,5250,78.30,21.70,60.41
8,East Africa,Second Class,362,279,74,9,2.44,4,218,353,79.04,20.96,60.22
9,West Asia,Second Class,1204,921,236,47,2.47,4,721,1157,79.60,20.40,59.88
10,North Africa,Second Class,617,483,107,27,2.42,4,369,590,81.86,18.14,59.81
11,West of USA,Second Class,1632,1254,310,68,2.47,4,969,1564,80.18,19.82,59.38
12,Caribbean,Second Class,1631,1277,271,83,2.48,4,965,1548,82.49,17.51,59.17
13,Southeast Asia,Second Class,1833,1395,358,80,2.46,4,1077,1753,79.58,20.42,58.76
14,Northern Europe,Second Class,1953,1489,390,74,2.47,4,1144,1879,79.24,20.76,58.58
15,East of USA,Second Class,1278,956,266,56,2.51,4,746,1222,78.23,21.77,58.37
16,South America,Second Class,2827,2122,578,127,2.55,4,1648,2700,78.59,21.41,58.30
17,Oceania,Second Class,2035,1562,403,70,2.44,4,1183,1965,79.49,20.51,58.13
18,Southern Europe,Second Class,1698,1293,337,68,2.44,4,969,1630,79.33,20.67,57.07
19,West Africa,Second Class,738,570,148,20,2.48,4,419,718,79.39,20.61,56.78

In [54]:
# ==========================================
# DAY 5 - STEP 3
# DELIVERY STATUS × SHIPPING MODE
# ==========================================

status_mode = (
    pd.crosstab(
        df["Shipping Mode"],
        df["Delivery Status"]
    )
    .reset_index()
)

# Ensure all expected columns exist
expected_statuses = [
    "Late delivery",
    "Advance shipping",
    "Shipping on time",
    "Shipping canceled"
]

for status in expected_statuses:
    if status not in status_mode.columns:
        status_mode[status] = 0

# Rename columns
status_mode = status_mode.rename(
    columns={
        "Late delivery": "Late_Delivery",
        "Advance shipping": "Advance_Shipping",
        "Shipping on time": "Shipping_On_Time",
        "Shipping canceled": "Shipping_Canceled"
    }
)

# Total shipments
status_mode["Total_Shipments"] = (
    status_mode["Late_Delivery"]
    + status_mode["Advance_Shipping"]
    + status_mode["Shipping_On_Time"]
    + status_mode["Shipping_Canceled"]
)

# Calculate percentages
status_mode["Late_%"] = (
    status_mode["Late_Delivery"]
    / status_mode["Total_Shipments"]
    * 100
)

status_mode["Advance_%"] = (
    status_mode["Advance_Shipping"]
    / status_mode["Total_Shipments"]
    * 100
)

status_mode["On_Time_%"] = (
    status_mode["Shipping_On_Time"]
    / status_mode["Total_Shipments"]
    * 100
)

status_mode["Canceled_%"] = (
    status_mode["Shipping_Canceled"]
    / status_mode["Total_Shipments"]
    * 100
)

# Round percentages
percentage_columns = [
    "Late_%",
    "Advance_%",
    "On_Time_%",
    "Canceled_%"
]

status_mode[percentage_columns] = (
    status_mode[percentage_columns].round(2)
)

print("==========================================")
print("DELIVERY STATUS × SHIPPING MODE")
print("==========================================")

display(status_mode)

==========================================
DELIVERY STATUS × SHIPPING MODE
==========================================

Delivery Status,Shipping Mode,Advance_Shipping,Late_Delivery,Shipping_Canceled,Shipping_On_Time,Total_Shipments,Late_%,Advance_%,On_Time_%,Canceled_%
0,First Class,0,26513,1301,0,27814,95.32,0.0,0.00,4.68
1,Same Day,0,4454,444,4839,9737,45.74,0.0,49.70,4.56
2,Second Class,0,26987,1410,6819,35216,76.63,0.0,19.36,4.00
3,Standard Class,41592,41023,4599,20538,107752,38.07,38.6,19.06,4.27

In [55]:
# ==========================================
# DAY 5 - STEP 4
# DELAY SEVERITY DISTRIBUTION
# ==========================================

delay_severity = (
    df[df["Delay Gap"] > 0]
    .groupby("Delay Gap")
    .size()
    .reset_index(name="Delayed_Shipments")
)

# Total delayed shipments
total_delayed = delay_severity["Delayed_Shipments"].sum()

# Percentage of all shipments
delay_severity["Share_of_All_Shipments_%"] = (
    delay_severity["Delayed_Shipments"]
    / len(df)
    * 100
)

# Percentage of delayed shipments
delay_severity["Share_of_Delayed_Shipments_%"] = (
    delay_severity["Delayed_Shipments"]
    / total_delayed
    * 100
)

# Severity label
delay_severity["Severity"] = (
    delay_severity["Delay Gap"]
    .map({
        1: "Minor Delay (+1 day)",
        2: "Moderate Delay (+2 days)",
        3: "Severe Delay (+3 days)",
        4: "Severe Delay (+4 days)"
    })
)

# Round
delay_severity[
    [
        "Share_of_All_Shipments_%",
        "Share_of_Delayed_Shipments_%"
    ]
] = (
    delay_severity[
        [
            "Share_of_All_Shipments_%",
            "Share_of_Delayed_Shipments_%"
        ]
    ].round(2)
)

print("==========================================")
print("DELAY SEVERITY DISTRIBUTION")
print("==========================================")

display(delay_severity)

==========================================
DELAY SEVERITY DISTRIBUTION
==========================================

,Delay Gap,Delayed_Shipments,Share_of_All_Shipments_%,Share_of_Delayed_Shipments_%,Severity
0,1,60647,33.60,58.65,Minor Delay (+1 day)
1,2,28718,15.91,27.77,Moderate Delay (+2 days)
2,3,7052,3.91,6.82,Severe Delay (+3 days)
3,4,6983,3.87,6.75,Severe Delay (+4 days)

In [56]:
# ==========================================
# DAY 5 - STEP 5
# PRODUCT / CATEGORY ANALYSIS
# ==========================================

category_analysis = (
    df.groupby("Category Name")
    .agg(
        Total_Shipments=("Delivery Performance", "size"),
        Delayed=("Delivery Performance", lambda x: (x == "Delayed").sum()),
        On_Time=("Delivery Performance", lambda x: (x == "On-Time").sum()),
        Early=("Delivery Performance", lambda x: (x == "Early").sum()),
        Canceled=("Delivery Performance", lambda x: (x == "Canceled").sum()),
        Avg_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
category_analysis["Non_Canceled"] = (
    category_analysis["Total_Shipments"]
    - category_analysis["Canceled"]
)

# Delay rate
category_analysis["Delay_Rate_%"] = (
    category_analysis["Delayed"]
    / category_analysis["Non_Canceled"]
    * 100
)

# On-time rate
category_analysis["On_Time_Rate_%"] = (
    category_analysis["On_Time"]
    / category_analysis["Non_Canceled"]
    * 100
)

# Average delay among delayed shipments
category_delay_avg = (
    df[df["Delivery Performance"] == "Delayed"]
    .groupby("Category Name")["Delay Gap"]
    .mean()
    .reset_index(name="Avg_Delay_When_Delayed")
)

category_analysis = category_analysis.merge(
    category_delay_avg,
    on="Category Name",
    how="left"
)

# Round numerical metrics
percentage_columns = [
    "Avg_Delay_Gap",
    "Delay_Rate_%",
    "On_Time_Rate_%",
    "Avg_Delay_When_Delayed"
]

category_analysis[percentage_columns] = (
    category_analysis[percentage_columns].round(2)
)

# Sort by delay rate
category_analysis = category_analysis.sort_values(
    "Delay_Rate_%",
    ascending=False
)

print("==========================================")
print("CATEGORY DELIVERY ANALYSIS")
print("==========================================")

display(category_analysis)

==========================================
CATEGORY DELIVERY ANALYSIS
==========================================

,Category Name,Total_Shipments,Delayed,On_Time,Early,Canceled,Avg_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Avg_Delay_When_Delayed
23,Golf Bags & Carts,61,42,7,12,0,0.77,61,68.85,11.48,1.55
32,Lacrosse,343,206,48,75,14,0.66,329,62.61,14.59,1.57
37,Pet Supplies,492,290,91,91,20,0.71,472,61.44,19.28,1.60
8,Cameras,592,344,92,126,30,0.65,562,61.21,16.37,1.56
0,Accessories,1780,1014,277,406,83,0.59,1697,59.75,16.32,1.60
36,Music,434,248,72,97,17,0.57,417,59.47,17.27,1.57
19,Fitness Accessories,309,176,51,69,13,0.61,296,59.46,17.23,1.62
6,Boxing & MMA,423,238,80,84,21,0.67,402,59.20,19.90,1.64
15,Crafts,484,271,83,104,26,0.63,458,59.17,18.12,1.62
1,As Seen on TV!,68,39,12,15,2,0.66,66,59.09,18.18,1.79
40,Sporting Goods,357,198,55,83,21,0.62,336,58.93,16.37,1.64
41,Strength Training,111,64,23,22,2,0.67,109,58.72,21.10,1.62
5,Books,405,229,75,87,14,0.53,391,58.57,19.18,1.53
44,Trade-In,974,542,152,232,48,0.63,926,58.53,16.41,1.73
17,Electronics,3156,1770,521,733,132,0.57,3024,58.53,17.23,1.59
25,Golf Gloves,1070,602,187,240,41,0.62,1029,58.50,18.17,1.63
21,Girls' Apparel,1201,664,189,284,64,0.59,1137,58.40,16.62,1.62
27,Health and Beauty,362,202,61,83,16,0.53,346,58.38,17.63,1.51
42,Tennis & Racquet,328,183,66,65,14,0.65,314,58.28,21.02,1.67
29,Hunting & Shooting,440,247,76,101,16,0.56,424,58.25,17.92,1.54
14,Consumer Electronics,431,238,70,101,22,0.64,409,58.19,17.11,1.73
48,Women's Clothing,650,367,119,145,19,0.65,631,58.16,18.86,1.70
26,Golf Shoes,524,291,91,120,22,0.58,502,57.97,18.13,1.62
20,Garden,484,270,80,116,18,0.55,466,57.94,17.17,1.64
4,Basketball,67,37,5,22,3,0.48,64,57.81,7.81,1.73
38,Shop By Sport,10984,6058,1921,2536,469,0.58,10515,57.61,18.27,1.63
31,Kids' Golf Clubs,384,205,67,84,28,0.62,356,57.58,18.82,1.63
3,Baseball & Softball,632,349,117,141,25,0.58,607,57.50,19.28,1.68
43,Toys,529,291,93,123,22,0.55,507,57.40,18.34,1.57
12,Cleats,24551,13496,4448,5570,1037,0.58,23514,57.40,18.92,1.63
24,Golf Balls,1475,805,241,357,72,0.55,1403,57.38,17.18,1.63
18,Fishing,17325,9516,3045,4034,730,0.56,16595,57.34,18.35,1.61
46,Water Sports,15540,8517,2816,3547,660,0.57,14880,57.24,18.92,1.61
30,Indoor/Outdoor Games,19298,10565,3454,4451,828,0.56,18470,57.20,18.70,1.62
33,Men's Clothing,208,113,34,51,10,0.51,198,57.07,17.17,1.56
49,Women's Golf Clubs,181,97,26,47,11,0.56,170,57.06,15.29,1.75
47,Women's Apparel,21035,11476,3754,4886,919,0.56,20116,57.05,18.66,1.61
34,Men's Footwear,22246,12121,4038,5104,983,0.56,21263,57.01,18.99,1.63
10,Cardio Equipment,12487,6805,2222,2921,539,0.55,11948,56.96,18.60,1.61
9,Camping & Hiking,13729,7487,2523,3147,572,0.55,13157,56.91,19.18,1.61
45,Video Games,838,455,159,190,34,0.58,804,56.59,19.78,1.67
16,DVDs,483,259,85,115,24,0.53,459,56.43,18.52,1.62
28,Hockey,614,329,101,158,26,0.47,588,55.95,17.18,1.54
11,Children's Clothing,652,348,117,157,30,0.58,622,55.95,18.81,1.70
39,Soccer,138,75,33,28,2,0.72,136,55.15,24.26,1.87
2,Baby,207,109,40,49,9,0.44,198,55.05,20.20,1.48
7,CDs,271,141,55,67,8,0.46,263,53.61,20.91,1.53
22,Golf Apparel,441,229,84,116,12,0.47,429,53.38,19.58,1.63
13,Computers,442,224,84,117,17,0.45,425,52.71,19.76,1.66
35,Men's Golf Clubs,283,135,56,83,9,0.33,274,49.27,20.44,1.61

In [57]:
# ==========================================
# DAY 5 - STEP 6
# DEPARTMENT ANALYSIS
# ==========================================

department_analysis = (
    df.groupby("Department Name")
    .agg(
        Total_Shipments=("Delivery Performance", "size"),
        Delayed=("Delivery Performance", lambda x: (x == "Delayed").sum()),
        On_Time=("Delivery Performance", lambda x: (x == "On-Time").sum()),
        Early=("Delivery Performance", lambda x: (x == "Early").sum()),
        Canceled=("Delivery Performance", lambda x: (x == "Canceled").sum()),
        Avg_Delay_Gap=("Delay Gap", "mean")
    )
    .reset_index()
)

# Non-canceled shipments
department_analysis["Non_Canceled"] = (
    department_analysis["Total_Shipments"]
    - department_analysis["Canceled"]
)

# Delay rate
department_analysis["Delay_Rate_%"] = (
    department_analysis["Delayed"]
    / department_analysis["Non_Canceled"]
    * 100
)

# On-time rate
department_analysis["On_Time_Rate_%"] = (
    department_analysis["On_Time"]
    / department_analysis["Non_Canceled"]
    * 100
)

# Average delay among delayed shipments
department_delay_avg = (
    df[df["Delivery Performance"] == "Delayed"]
    .groupby("Department Name")["Delay Gap"]
    .mean()
    .reset_index(name="Avg_Delay_When_Delayed")
)

department_analysis = department_analysis.merge(
    department_delay_avg,
    on="Department Name",
    how="left"
)

# Round metrics
round_columns = [
    "Avg_Delay_Gap",
    "Delay_Rate_%",
    "On_Time_Rate_%",
    "Avg_Delay_When_Delayed"
]

department_analysis[round_columns] = (
    department_analysis[round_columns].round(2)
)

# Sort by delay rate
department_analysis = department_analysis.sort_values(
    "Delay_Rate_%",
    ascending=False
)

print("==========================================")
print("DEPARTMENT DELIVERY ANALYSIS")
print("==========================================")

display(department_analysis)

==========================================
DEPARTMENT DELIVERY ANALYSIS
==========================================

,Department Name,Total_Shipments,Delayed,On_Time,Early,Canceled,Avg_Delay_Gap,Non_Canceled,Delay_Rate_%,On_Time_Rate_%,Avg_Delay_When_Delayed
9,Pet Shop,492,290,91,91,20,0.71,472,61.44,19.28,1.60
1,Book Shop,405,229,75,87,14,0.53,391,58.57,19.18,1.53
7,Health and Beauty,362,202,61,83,16,0.53,346,58.38,17.63,1.51
4,Fitness,2479,1377,425,572,105,0.58,2374,58.00,17.90,1.63
8,Outdoors,9686,5375,1603,2289,419,0.57,9267,58.00,17.30,1.63
10,Technology,1465,806,246,344,69,0.59,1396,57.74,17.62,1.63
6,Golf,33220,18198,5864,7706,1452,0.57,31768,57.28,18.46,1.62
0,Apparel,48998,26825,8879,11180,2114,0.57,46884,57.22,18.94,1.63
5,Footwear,14525,7949,2574,3368,634,0.56,13891,57.22,18.53,1.61
3,Fan Shop,66861,36623,12007,15403,2828,0.56,64033,57.19,18.75,1.61
2,Discs Shop,2026,1103,371,469,83,0.55,1943,56.77,19.09,1.62

In [58]:
# ==========================================
# DAY 5 - STEP 7
# BUSINESS IMPACT ANALYSIS
# ==========================================

business_impact = (
    df.groupby("Delivery Performance")
    .agg(
        Shipments=("Delivery Performance", "size"),
        Total_Sales=("Sales", "sum"),
        Avg_Sales=("Sales", "mean"),
        Total_Profit=("Order Profit Per Order", "sum"),
        Avg_Profit=("Order Profit Per Order", "mean"),
        Avg_Order_Value=("Order Item Total", "mean"),
        Avg_Quantity=("Order Item Quantity", "mean"),
        Avg_Discount_Rate=("Order Item Discount Rate", "mean"),
        Avg_Benefit_Per_Order=("Benefit per order", "mean")
    )
    .reset_index()
)

# Percentage of total shipments
business_impact["Shipment_Share_%"] = (
    business_impact["Shipments"]
    / len(df)
    * 100
)

# Percentage of total sales
total_sales = df["Sales"].sum()

business_impact["Sales_Share_%"] = (
    business_impact["Total_Sales"]
    / total_sales
    * 100
)

# Round metrics
round_columns = [
    "Total_Sales",
    "Avg_Sales",
    "Total_Profit",
    "Avg_Profit",
    "Avg_Order_Value",
    "Avg_Quantity",
    "Avg_Discount_Rate",
    "Avg_Benefit_Per_Order",
    "Shipment_Share_%",
    "Sales_Share_%"
]

business_impact[round_columns] = (
    business_impact[round_columns].round(2)
)

print("==========================================")
print("BUSINESS IMPACT BY DELIVERY PERFORMANCE")
print("==========================================")

display(business_impact)

==========================================
BUSINESS IMPACT BY DELIVERY PERFORMANCE
==========================================

,Delivery Performance,Shipments,Total_Sales,Avg_Sales,Total_Profit,Avg_Profit,Avg_Order_Value,Avg_Quantity,Avg_Discount_Rate,Avg_Benefit_Per_Order,Shipment_Share_%,Sales_Share_%
0,Canceled,7754,1570305.33,202.52,160482.34,20.70,181.81,2.13,0.1,20.70,4.30,4.27
1,Delayed,98977,20126394.88,203.34,2140051.68,21.62,182.69,2.13,0.1,21.62,54.83,54.71
2,Early,41592,8518007.73,204.80,935225.28,22.49,184.08,2.13,0.1,22.49,23.04,23.16
3,On-Time,32196,6570026.37,204.06,731143.67,22.71,183.43,2.12,0.1,22.71,17.84,17.86

In [60]:
# ==========================================
# DAY 5 - STEP 7
# BUSINESS IMPACT ANALYSIS
# ==========================================

business_impact = (
    df.groupby("Delivery Performance")
    .agg(
        Shipments=("Delivery Performance", "size"),
        Total_Sales=("Sales", "sum"),
        Avg_Sales=("Sales", "mean"),
        Total_Profit=("Order Profit Per Order", "sum"),
        Avg_Profit=("Order Profit Per Order", "mean"),
        Avg_Order_Value=("Order Item Total", "mean"),
        Avg_Quantity=("Order Item Quantity", "mean"),
        Avg_Discount_Rate=("Order Item Discount Rate", "mean"),
        Avg_Benefit_Per_Order=("Benefit per order", "mean")
    )
    .reset_index()
)

# Percentage of total shipments
business_impact["Shipment_Share_%"] = (
    business_impact["Shipments"]
    / len(df)
    * 100
)

# Percentage of total sales
total_sales = df["Sales"].sum()

business_impact["Sales_Share_%"] = (
    business_impact["Total_Sales"]
    / total_sales
    * 100
)

# Round metrics
round_columns = [
    "Total_Sales",
    "Avg_Sales",
    "Total_Profit",
    "Avg_Profit",
    "Avg_Order_Value",
    "Avg_Quantity",
    "Avg_Discount_Rate",
    "Avg_Benefit_Per_Order",
    "Shipment_Share_%",
    "Sales_Share_%"
]

business_impact[round_columns] = (
    business_impact[round_columns].round(2)
)

print("==========================================")
print("BUSINESS IMPACT BY DELIVERY PERFORMANCE")
print("==========================================")

display(business_impact)

==========================================
BUSINESS IMPACT BY DELIVERY PERFORMANCE
==========================================

,Delivery Performance,Shipments,Total_Sales,Avg_Sales,Total_Profit,Avg_Profit,Avg_Order_Value,Avg_Quantity,Avg_Discount_Rate,Avg_Benefit_Per_Order,Shipment_Share_%,Sales_Share_%
0,Canceled,7754,1570305.33,202.52,160482.34,20.70,181.81,2.13,0.1,20.70,4.30,4.27
1,Delayed,98977,20126394.88,203.34,2140051.68,21.62,182.69,2.13,0.1,21.62,54.83,54.71
2,Early,41592,8518007.73,204.80,935225.28,22.49,184.08,2.13,0.1,22.49,23.04,23.16
3,On-Time,32196,6570026.37,204.06,731143.67,22.71,183.43,2.12,0.1,22.71,17.84,17.86

In [61]:
# ==========================================
# DAY 5 - STEP 8
# FINAL RISK DRIVER SUMMARY
# ==========================================

risk_driver_summary = []

# ------------------------------------------------
# 1. SHIPPING MODE
# ------------------------------------------------

mode_range = (
    shipping_mode_deep_dive["Delay Rate"].max()
    - shipping_mode_deep_dive["Delay Rate"].min()
)

mode_min = shipping_mode_deep_dive.loc[
    shipping_mode_deep_dive["Delay Rate"].idxmin(),
    "Shipping Mode"
]

mode_max = shipping_mode_deep_dive.loc[
    shipping_mode_deep_dive["Delay Rate"].idxmax(),
    "Shipping Mode"
]

risk_driver_summary.append({
    "Driver": "Shipping Mode",
    "Metric": "Delay Rate",
    "Minimum_%": round(shipping_mode_deep_dive["Delay Rate"].min(), 2),
    "Maximum_%": round(shipping_mode_deep_dive["Delay Rate"].max(), 2),
    "Range_pp": round(mode_range, 2),
    "Lowest_Risk_Group": mode_min,
    "Highest_Risk_Group": mode_max,
    "Assessment": "Strong"
})


# ------------------------------------------------
# 2. CUSTOMER SEGMENT
# ------------------------------------------------

segment_range = (
    segment_analysis["Delay_Rate_%"].max()
    - segment_analysis["Delay_Rate_%"].min()
)

segment_min = segment_analysis.loc[
    segment_analysis["Delay_Rate_%"].idxmin(),
    "Customer Segment"
]

segment_max = segment_analysis.loc[
    segment_analysis["Delay_Rate_%"].idxmax(),
    "Customer Segment"
]

risk_driver_summary.append({
    "Driver": "Customer Segment",
    "Metric": "Delay Rate",
    "Minimum_%": round(segment_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(segment_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(segment_range, 2),
    "Lowest_Risk_Group": segment_min,
    "Highest_Risk_Group": segment_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 3. MARKET
# ------------------------------------------------

market_range = (
    market_analysis["Delay Rate"].max()
    - market_analysis["Delay Rate"].min()
)

market_min = market_analysis.loc[
    market_analysis["Delay Rate"].idxmin(),
    "Market"
]

market_max = market_analysis.loc[
    market_analysis["Delay Rate"].idxmax(),
    "Market"
]

risk_driver_summary.append({
    "Driver": "Market",
    "Metric": "Delay Rate",
    "Minimum_%": round(market_analysis["Delay Rate"].min(), 2),
    "Maximum_%": round(market_analysis["Delay Rate"].max(), 2),
    "Range_pp": round(market_range, 2),
    "Lowest_Risk_Group": market_min,
    "Highest_Risk_Group": market_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 4. DEPARTMENT
# ------------------------------------------------

department_range = (
    department_analysis["Delay_Rate_%"].max()
    - department_analysis["Delay_Rate_%"].min()
)

department_min = department_analysis.loc[
    department_analysis["Delay_Rate_%"].idxmin(),
    "Department Name"
]

department_max = department_analysis.loc[
    department_analysis["Delay_Rate_%"].idxmax(),
    "Department Name"
]

risk_driver_summary.append({
    "Driver": "Department",
    "Metric": "Delay Rate",
    "Minimum_%": round(department_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(department_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(department_range, 2),
    "Lowest_Risk_Group": department_min,
    "Highest_Risk_Group": department_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 5. CATEGORY
# ------------------------------------------------

category_range = (
    category_analysis["Delay_Rate_%"].max()
    - category_analysis["Delay_Rate_%"].min()
)

category_min = category_analysis.loc[
    category_analysis["Delay_Rate_%"].idxmin(),
    "Category Name"
]

category_max = category_analysis.loc[
    category_analysis["Delay_Rate_%"].idxmax(),
    "Category Name"
]

risk_driver_summary.append({
    "Driver": "Category",
    "Metric": "Delay Rate",
    "Minimum_%": round(category_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(category_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(category_range, 2),
    "Lowest_Risk_Group": category_min,
    "Highest_Risk_Group": category_max,
    "Assessment": "Moderate"
})


# ------------------------------------------------
# FINAL TABLE
# ------------------------------------------------

risk_driver_summary = pd.DataFrame(
    risk_driver_summary
)

risk_driver_summary = risk_driver_summary.sort_values(
    "Range_pp",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("FINAL RISK DRIVER SUMMARY")
print("==========================================")

display(risk_driver_summary)

KeyError: 'Delay Rate'

In [62]:
print("Shipping Mode Deep Dive columns:")
print(shipping_mode_deep_dive.columns.tolist())

Shipping Mode Deep Dive columns:
['Shipping Mode', 'Total_Shipments', 'Delayed_Shipments', 'On_Time_Shipments', 'Early_Shipments', 'Canceled_Shipments', 'Avg_Delay_When_Delayed', 'Max_Delay', 'Severe_Delays_2Plus', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Severe_Delay_Rate_%', 'Efficiency_Index']

In [63]:
# ==========================================
# DAY 5 - STEP 8
# FINAL RISK DRIVER SUMMARY
# ==========================================

risk_driver_summary = []

# ------------------------------------------------
# 1. SHIPPING MODE
# ------------------------------------------------

mode_range = (
    shipping_mode_deep_dive["Delay_Rate_%"].max()
    - shipping_mode_deep_dive["Delay_Rate_%"].min()
)

mode_min = shipping_mode_deep_dive.loc[
    shipping_mode_deep_dive["Delay_Rate_%"].idxmin(),
    "Shipping Mode"
]

mode_max = shipping_mode_deep_dive.loc[
    shipping_mode_deep_dive["Delay_Rate_%"].idxmax(),
    "Shipping Mode"
]

risk_driver_summary.append({
    "Driver": "Shipping Mode",
    "Metric": "Delay Rate",
    "Minimum_%": round(
        shipping_mode_deep_dive["Delay_Rate_%"].min(), 2
    ),
    "Maximum_%": round(
        shipping_mode_deep_dive["Delay_Rate_%"].max(), 2
    ),
    "Range_pp": round(mode_range, 2),
    "Lowest_Risk_Group": mode_min,
    "Highest_Risk_Group": mode_max,
    "Assessment": "Strong"
})


# ------------------------------------------------
# 2. CUSTOMER SEGMENT
# ------------------------------------------------

segment_range = (
    segment_analysis["Delay_Rate_%"].max()
    - segment_analysis["Delay_Rate_%"].min()
)

segment_min = segment_analysis.loc[
    segment_analysis["Delay_Rate_%"].idxmin(),
    "Customer Segment"
]

segment_max = segment_analysis.loc[
    segment_analysis["Delay_Rate_%"].idxmax(),
    "Customer Segment"
]

risk_driver_summary.append({
    "Driver": "Customer Segment",
    "Metric": "Delay Rate",
    "Minimum_%": round(
        segment_analysis["Delay_Rate_%"].min(), 2
    ),
    "Maximum_%": round(
        segment_analysis["Delay_Rate_%"].max(), 2
    ),
    "Range_pp": round(segment_range, 2),
    "Lowest_Risk_Group": segment_min,
    "Highest_Risk_Group": segment_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 3. MARKET
# ------------------------------------------------

market_range = (
    market_analysis["Delay Rate"].max()
    - market_analysis["Delay Rate"].min()
)

market_min = market_analysis.loc[
    market_analysis["Delay Rate"].idxmin(),
    "Market"
]

market_max = market_analysis.loc[
    market_analysis["Delay Rate"].idxmax(),
    "Market"
]

risk_driver_summary.append({
    "Driver": "Market",
    "Metric": "Delay Rate",
    "Minimum_%": round(
        market_analysis["Delay Rate"].min(), 2
    ),
    "Maximum_%": round(
        market_analysis["Delay Rate"].max(), 2
    ),
    "Range_pp": round(market_range, 2),
    "Lowest_Risk_Group": market_min,
    "Highest_Risk_Group": market_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 4. DEPARTMENT
# ------------------------------------------------

department_range = (
    department_analysis["Delay_Rate_%"].max()
    - department_analysis["Delay_Rate_%"].min()
)

department_min = department_analysis.loc[
    department_analysis["Delay_Rate_%"].idxmin(),
    "Department Name"
]

department_max = department_analysis.loc[
    department_analysis["Delay_Rate_%"].idxmax(),
    "Department Name"
]

risk_driver_summary.append({
    "Driver": "Department",
    "Metric": "Delay Rate",
    "Minimum_%": round(
        department_analysis["Delay_Rate_%"].min(), 2
    ),
    "Maximum_%": round(
        department_analysis["Delay_Rate_%"].max(), 2
    ),
    "Range_pp": round(department_range, 2),
    "Lowest_Risk_Group": department_min,
    "Highest_Risk_Group": department_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 5. CATEGORY
# ------------------------------------------------

category_range = (
    category_analysis["Delay_Rate_%"].max()
    - category_analysis["Delay_Rate_%"].min()
)

category_min = category_analysis.loc[
    category_analysis["Delay_Rate_%"].idxmin(),
    "Category Name"
]

category_max = category_analysis.loc[
    category_analysis["Delay_Rate_%"].idxmax(),
    "Category Name"
]

risk_driver_summary.append({
    "Driver": "Category",
    "Metric": "Delay Rate",
    "Minimum_%": round(
        category_analysis["Delay_Rate_%"].min(), 2
    ),
    "Maximum_%": round(
        category_analysis["Delay_Rate_%"].max(), 2
    ),
    "Range_pp": round(category_range, 2),
    "Lowest_Risk_Group": category_min,
    "Highest_Risk_Group": category_max,
    "Assessment": "Moderate"
})


# ------------------------------------------------
# FINAL TABLE
# ------------------------------------------------

risk_driver_summary = pd.DataFrame(
    risk_driver_summary
)

risk_driver_summary = risk_driver_summary.sort_values(
    "Range_pp",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("FINAL RISK DRIVER SUMMARY")
print("==========================================")

display(risk_driver_summary)

KeyError: 'Delay Rate'

In [64]:
print("Market Analysis columns:")
print(market_analysis.columns.tolist())

Market Analysis columns:
['Market', 'Total_Shipments', 'Delayed_Shipments', 'On_Time_Shipments', 'Early_Shipments', 'Canceled_Shipments', 'Average_Delay_Gap', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Cancellation_Rate_%', 'Market_Delay_Index']

In [65]:
print("Department columns:")
print(department_analysis.columns.tolist())

print("\nCategory columns:")
print(category_analysis.columns.tolist())

Department columns:
['Department Name', 'Total_Shipments', 'Delayed', 'On_Time', 'Early', 'Canceled', 'Avg_Delay_Gap', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Avg_Delay_When_Delayed']

Category columns:
['Category Name', 'Total_Shipments', 'Delayed', 'On_Time', 'Early', 'Canceled', 'Avg_Delay_Gap', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Avg_Delay_When_Delayed']

In [66]:
# ==========================================
# DAY 5 - STEP 8
# FINAL RISK DRIVER SUMMARY
# ==========================================

risk_driver_summary = []

# ------------------------------------------------
# 1. SHIPPING MODE
# ------------------------------------------------

mode_range = (
    shipping_mode_deep_dive["Delay_Rate_%"].max()
    - shipping_mode_deep_dive["Delay_Rate_%"].min()
)

mode_min = shipping_mode_deep_dive.loc[
    shipping_mode_deep_dive["Delay_Rate_%"].idxmin(),
    "Shipping Mode"
]

mode_max = shipping_mode_deep_dive.loc[
    shipping_mode_deep_dive["Delay_Rate_%"].idxmax(),
    "Shipping Mode"
]

risk_driver_summary.append({
    "Driver": "Shipping Mode",
    "Metric": "Delay Rate",
    "Minimum_%": round(shipping_mode_deep_dive["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(shipping_mode_deep_dive["Delay_Rate_%"].max(), 2),
    "Range_pp": round(mode_range, 2),
    "Lowest_Risk_Group": mode_min,
    "Highest_Risk_Group": mode_max,
    "Assessment": "Strong"
})


# ------------------------------------------------
# 2. CUSTOMER SEGMENT
# ------------------------------------------------

segment_range = (
    segment_analysis["Delay_Rate_%"].max()
    - segment_analysis["Delay_Rate_%"].min()
)

segment_min = segment_analysis.loc[
    segment_analysis["Delay_Rate_%"].idxmin(),
    "Customer Segment"
]

segment_max = segment_analysis.loc[
    segment_analysis["Delay_Rate_%"].idxmax(),
    "Customer Segment"
]

risk_driver_summary.append({
    "Driver": "Customer Segment",
    "Metric": "Delay Rate",
    "Minimum_%": round(segment_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(segment_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(segment_range, 2),
    "Lowest_Risk_Group": segment_min,
    "Highest_Risk_Group": segment_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 3. MARKET
# ------------------------------------------------

market_range = (
    market_analysis["Delay_Rate_%"].max()
    - market_analysis["Delay_Rate_%"].min()
)

market_min = market_analysis.loc[
    market_analysis["Delay_Rate_%"].idxmin(),
    "Market"
]

market_max = market_analysis.loc[
    market_analysis["Delay_Rate_%"].idxmax(),
    "Market"
]

risk_driver_summary.append({
    "Driver": "Market",
    "Metric": "Delay Rate",
    "Minimum_%": round(market_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(market_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(market_range, 2),
    "Lowest_Risk_Group": market_min,
    "Highest_Risk_Group": market_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 4. DEPARTMENT
# ------------------------------------------------

department_range = (
    department_analysis["Delay_Rate_%"].max()
    - department_analysis["Delay_Rate_%"].min()
)

department_min = department_analysis.loc[
    department_analysis["Delay_Rate_%"].idxmin(),
    "Department Name"
]

department_max = department_analysis.loc[
    department_analysis["Delay_Rate_%"].idxmax(),
    "Department Name"
]

risk_driver_summary.append({
    "Driver": "Department",
    "Metric": "Delay Rate",
    "Minimum_%": round(department_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(department_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(department_range, 2),
    "Lowest_Risk_Group": department_min,
    "Highest_Risk_Group": department_max,
    "Assessment": "Weak"
})


# ------------------------------------------------
# 5. CATEGORY
# ------------------------------------------------

category_range = (
    category_analysis["Delay_Rate_%"].max()
    - category_analysis["Delay_Rate_%"].min()
)

category_min = category_analysis.loc[
    category_analysis["Delay_Rate_%"].idxmin(),
    "Category Name"
]

category_max = category_analysis.loc[
    category_analysis["Delay_Rate_%"].idxmax(),
    "Category Name"
]

risk_driver_summary.append({
    "Driver": "Category",
    "Metric": "Delay Rate",
    "Minimum_%": round(category_analysis["Delay_Rate_%"].min(), 2),
    "Maximum_%": round(category_analysis["Delay_Rate_%"].max(), 2),
    "Range_pp": round(category_range, 2),
    "Lowest_Risk_Group": category_min,
    "Highest_Risk_Group": category_max,
    "Assessment": "Moderate"
})


# ------------------------------------------------
# FINAL TABLE
# ------------------------------------------------

risk_driver_summary = pd.DataFrame(risk_driver_summary)

risk_driver_summary = risk_driver_summary.sort_values(
    "Range_pp",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("FINAL RISK DRIVER SUMMARY")
print("==========================================")

display(risk_driver_summary)

==========================================
FINAL RISK DRIVER SUMMARY
==========================================

,Driver,Metric,Minimum_%,Maximum_%,Range_pp,Lowest_Risk_Group,Highest_Risk_Group,Assessment
0,Shipping Mode,Delay Rate,39.77,100.00,60.23,Standard Class,First Class,Strong
1,Category,Delay Rate,49.27,68.85,19.58,Men's Golf Clubs,Golf Bags & Carts,Moderate
2,Department,Delay Rate,56.77,61.44,4.67,Discs Shop,Pet Shop,Weak
3,Market,Delay Rate,56.84,57.69,0.85,Africa,Europe,Weak
4,Customer Segment,Delay Rate,57.08,57.59,0.51,Corporate,Home Office,Weak

In [67]:
# ==========================================
# DAY 5 - STEP 9
# SAVE ALL DAY 5 ANALYSIS TABLES
# ==========================================

analysis_path = r"D:\APL_Logistics_Project\04_Analysis"

# 1. Shipping Mode Deep Dive
shipping_mode_deep_dive.to_csv(
    rf"{analysis_path}\Shipping_Mode_Deep_Dive.csv",
    index=False
)

# 2. Region × Shipping Mode Severity
region_mode_severity.to_csv(
    rf"{analysis_path}\Region_Mode_Severity.csv",
    index=False
)

# 3. Delivery Status × Shipping Mode
status_mode_analysis.to_csv(
    rf"{analysis_path}\Delivery_Status_Shipping_Mode.csv",
    index=False
)

# 4. Delay Severity Distribution
delay_severity.to_csv(
    rf"{analysis_path}\Delay_Severity_Distribution.csv",
    index=False
)

# 5. Category Analysis
category_analysis.to_csv(
    rf"{analysis_path}\Category_Analysis.csv",
    index=False
)

# 6. Department Analysis
department_analysis.to_csv(
    rf"{analysis_path}\Department_Analysis.csv",
    index=False
)

# 7. Business Impact Analysis
business_impact.to_csv(
    rf"{analysis_path}\Business_Impact_Analysis.csv",
    index=False
)

# 8. Final Risk Driver Summary
risk_driver_summary.to_csv(
    rf"{analysis_path}\Final_Risk_Driver_Summary.csv",
    index=False
)

print("==========================================")
print("DAY 5 FILES SAVED SUCCESSFULLY")
print("==========================================")

print("\nSaved files:")

print("1. Shipping_Mode_Deep_Dive.csv")
print("2. Region_Mode_Severity.csv")
print("3. Delivery_Status_Shipping_Mode.csv")
print("4. Delay_Severity_Distribution.csv")
print("5. Category_Analysis.csv")
print("6. Department_Analysis.csv")
print("7. Business_Impact_Analysis.csv")
print("8. Final_Risk_Driver_Summary.csv")

NameError: name 'status_mode_analysis' is not defined

In [68]:
print([
    name for name in globals()
    if "status" in name.lower() and "mode" in name.lower()
])

['status_mode']

In [69]:
# ==========================================
# DAY 5 - STEP 9
# SAVE ALL DAY 5 ANALYSIS TABLES
# ==========================================

analysis_path = r"D:\APL_Logistics_Project\04_Analysis"

# 1. Shipping Mode Deep Dive
shipping_mode_deep_dive.to_csv(
    rf"{analysis_path}\Shipping_Mode_Deep_Dive.csv",
    index=False
)

# 2. Region × Shipping Mode Severity
region_mode_severity.to_csv(
    rf"{analysis_path}\Region_Mode_Severity.csv",
    index=False
)

# 3. Delivery Status × Shipping Mode
status_mode.to_csv(
    rf"{analysis_path}\Delivery_Status_Shipping_Mode.csv",
    index=False
)

# 4. Delay Severity Distribution
delay_severity.to_csv(
    rf"{analysis_path}\Delay_Severity_Distribution.csv",
    index=False
)

# 5. Category Analysis
category_analysis.to_csv(
    rf"{analysis_path}\Category_Analysis.csv",
    index=False
)

# 6. Department Analysis
department_analysis.to_csv(
    rf"{analysis_path}\Department_Analysis.csv",
    index=False
)

# 7. Business Impact Analysis
business_impact.to_csv(
    rf"{analysis_path}\Business_Impact_Analysis.csv",
    index=False
)

# 8. Final Risk Driver Summary
risk_driver_summary.to_csv(
    rf"{analysis_path}\Final_Risk_Driver_Summary.csv",
    index=False
)

print("==========================================")
print("DAY 5 FILES SAVED SUCCESSFULLY")
print("==========================================")

print("\nSaved files:")

print("1. Shipping_Mode_Deep_Dive.csv")
print("2. Region_Mode_Severity.csv")
print("3. Delivery_Status_Shipping_Mode.csv")
print("4. Delay_Severity_Distribution.csv")
print("5. Category_Analysis.csv")
print("6. Department_Analysis.csv")
print("7. Business_Impact_Analysis.csv")
print("8. Final_Risk_Driver_Summary.csv")

==========================================
DAY 5 FILES SAVED SUCCESSFULLY
==========================================

Saved files:
1. Shipping_Mode_Deep_Dive.csv
2. Region_Mode_Severity.csv
3. Delivery_Status_Shipping_Mode.csv
4. Delay_Severity_Distribution.csv
5. Category_Analysis.csv
6. Department_Analysis.csv
7. Business_Impact_Analysis.csv
8. Final_Risk_Driver_Summary.csv

In [70]:
# ==========================================
# DAY 6 - STEP 1
# LOAD ANALYSIS DATA
# ==========================================

import pandas as pd
import numpy as np
import os

analysis_path = r"D:\APL_Logistics_Project\04_Analysis"

# Load main analysis dataset
analysis_file = rf"{analysis_path}\APL_Logistics_Analysis.csv"

analysis_df = pd.read_csv(
    analysis_file,
    encoding="utf-8-sig"
)

print("==========================================")
print("DAY 6 - DATA LOADED")
print("==========================================")

print("Shape:", analysis_df.shape)

print("\nColumns:")
print(analysis_df.columns.tolist())

print("\nFirst 5 rows:")
display(analysis_df.head())

==========================================
DAY 6 - DATA LOADED
==========================================
Shape: (180519, 42)

Columns:
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Product Name', 'Product Price', 'Shipping Mode', 'Delay Gap', 'Delivery Performance']

First 5 rows:

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode,Delay Gap,Delivery Performance
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class,2,Delayed
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class,0,On-Time
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class,0,On-Time
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class,2,Delayed
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class,2,Delayed

In [71]:
# ==========================================
# DAY 6 - STEP 2
# MASTER KPI SUMMARY
# ==========================================

total_shipments = len(analysis_df)

delayed_shipments = (
    analysis_df["Delivery Performance"] == "Delayed"
).sum()

on_time_shipments = (
    analysis_df["Delivery Performance"] == "On-Time"
).sum()

early_shipments = (
    analysis_df["Delivery Performance"] == "Early"
).sum()

canceled_shipments = (
    analysis_df["Delivery Performance"] == "Canceled"
).sum()

non_canceled = total_shipments - canceled_shipments


# ------------------------------------------
# KPI CALCULATIONS
# ------------------------------------------

delay_rate = (
    delayed_shipments / non_canceled * 100
)

on_time_rate = (
    on_time_shipments / non_canceled * 100
)

early_rate = (
    early_shipments / non_canceled * 100
)

cancellation_rate = (
    canceled_shipments / total_shipments * 100
)

average_delay_gap = (
    analysis_df["Delay Gap"].mean()
)

delayed_only = analysis_df[
    analysis_df["Delivery Performance"] == "Delayed"
]

average_delay_when_delayed = (
    delayed_only["Delay Gap"].mean()
)

late_delivery_risk = (
    analysis_df["Late_delivery_risk"].mean() * 100
)


# ------------------------------------------
# CREATE KPI TABLE
# ------------------------------------------

kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Shipments",
        "Delayed Shipments",
        "On-Time Shipments",
        "Early Shipments",
        "Canceled Shipments",
        "Delay Rate (%)",
        "On-Time Rate (%)",
        "Early Rate (%)",
        "Cancellation Rate (%)",
        "Average Delay Gap (Days)",
        "Average Delay When Delayed (Days)",
        "Late Delivery Risk (%)"
    ],

    "Value": [
        total_shipments,
        delayed_shipments,
        on_time_shipments,
        early_shipments,
        canceled_shipments,
        round(delay_rate, 2),
        round(on_time_rate, 2),
        round(early_rate, 2),
        round(cancellation_rate, 2),
        round(average_delay_gap, 2),
        round(average_delay_when_delayed, 2),
        round(late_delivery_risk, 2)
    ]
})


# ------------------------------------------
# DISPLAY
# ------------------------------------------

print("==========================================")
print("DAY 6 - MASTER KPI SUMMARY")
print("==========================================")

display(kpi_summary)

==========================================
DAY 6 - MASTER KPI SUMMARY
==========================================

                                  KPI      Value
0                     Total Shipments  180519.00
1                   Delayed Shipments   98977.00
2                   On-Time Shipments   32196.00
3                     Early Shipments   41592.00
4                  Canceled Shipments    7754.00
5                      Delay Rate (%)      57.29
6                    On-Time Rate (%)      18.64
7                      Early Rate (%)      24.07
8               Cancellation Rate (%)       4.30
9            Average Delay Gap (Days)       0.57
10  Average Delay When Delayed (Days)       1.62
11             Late Delivery Risk (%)      54.83

In [72]:
# ==========================================
# DAY 6 - STEP 3
# DELIVERY PERFORMANCE VISUALIZATION DATA
# ==========================================

delivery_performance_viz = (
    analysis_df["Delivery Performance"]
    .value_counts()
    .reindex(
        ["Delayed", "On-Time", "Early", "Canceled"],
        fill_value=0
    )
    .reset_index()
)

delivery_performance_viz.columns = [
    "Delivery Performance",
    "Shipments"
]

# Calculate percentage of all shipments
delivery_performance_viz["Percentage_%"] = (
    delivery_performance_viz["Shipments"]
    / len(analysis_df)
    * 100
)

delivery_performance_viz["Percentage_%"] = (
    delivery_performance_viz["Percentage_%"]
    .round(2)
)

print("==========================================")
print("DELIVERY PERFORMANCE VISUALIZATION DATA")
print("==========================================")

display(delivery_performance_viz)

==========================================
DELIVERY PERFORMANCE VISUALIZATION DATA
==========================================

  Delivery Performance  Shipments  Percentage_%
0              Delayed      98977         54.83
1              On-Time      32196         17.84
2                Early      41592         23.04
3             Canceled       7754          4.30

In [73]:
# ==========================================
# DAY 6 - STEP 4
# DELAY GAP DISTRIBUTION
# ==========================================

delay_gap_viz = (
    analysis_df[
        analysis_df["Delay Gap"] > 0
    ]["Delay Gap"]
    .value_counts()
    .sort_index()
    .reset_index()
)

delay_gap_viz.columns = [
    "Delay_Gap_Days",
    "Delayed_Shipments"
]

# Percentage of all delayed shipments
total_delayed = delay_gap_viz["Delayed_Shipments"].sum()

delay_gap_viz["Share_of_Delayed_%"] = (
    delay_gap_viz["Delayed_Shipments"]
    / total_delayed
    * 100
).round(2)

# Classify severity
delay_gap_viz["Severity"] = np.select(
    [
        delay_gap_viz["Delay_Gap_Days"] == 1,
        delay_gap_viz["Delay_Gap_Days"] == 2,
        delay_gap_viz["Delay_Gap_Days"] >= 3
    ],
    [
        "Minor Delay",
        "Moderate Delay",
        "Severe Delay"
    ],
    default="Unknown"
)

print("==========================================")
print("DELAY GAP DISTRIBUTION")
print("==========================================")

display(delay_gap_viz)

==========================================
DELAY GAP DISTRIBUTION
==========================================

   Delay_Gap_Days  Delayed_Shipments  Share_of_Delayed_%        Severity
0               1              60647               58.65     Minor Delay
1               2              28718               27.77  Moderate Delay
2               3               7052                6.82    Severe Delay
3               4               6983                6.75    Severe Delay

In [74]:
# ==========================================
# DAY 6 - STEP 5
# SHIPPING MODE VISUALIZATION DATA
# ==========================================

shipping_mode_viz = shipping_mode_deep_dive[
    [
        "Shipping Mode",
        "Total_Shipments",
        "Delayed_Shipments",
        "On_Time_Shipments",
        "Delay_Rate_%",
        "On_Time_Rate_%",
        "Efficiency_Index"
    ]
].copy()

# Sort by delay rate
shipping_mode_viz = shipping_mode_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("SHIPPING MODE VISUALIZATION DATA")
print("==========================================")

display(shipping_mode_viz)

==========================================
SHIPPING MODE VISUALIZATION DATA
==========================================

,Shipping Mode,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Delay_Rate_%,On_Time_Rate_%,Efficiency_Index
0,First Class,27814,26513,0,100.00,0.00,-100.00
1,Second Class,35216,26987,6819,79.83,20.17,-59.66
2,Same Day,9737,4454,4839,47.93,52.07,4.14
3,Standard Class,107752,41023,20538,39.77,19.91,-19.86

In [75]:
# ==========================================
# DAY 6 - STEP 6
# REGIONAL VISUALIZATION DATA
# ==========================================

regional_viz = regional_analysis[
    [
        "Order Region",
        "Total_Shipments",
        "Delayed",
        "On_Time",
        "Early",
        "Canceled",
        "Avg_Delay_Gap",
        "Delay_Rate_%",
        "On_Time_Rate_%"
    ]
].copy()

# Sort by delay rate
regional_viz = regional_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("REGIONAL VISUALIZATION DATA")
print("==========================================")

display(regional_viz.head(10))

KeyError: "['Delayed', 'On_Time', 'Early', 'Canceled', 'Avg_Delay_Gap'] not in index"

In [76]:
print("Regional Analysis columns:")
print(regional_analysis.columns.tolist())

Regional Analysis columns:
['Order Region', 'Total_Shipments', 'Delayed_Shipments', 'On_Time_Shipments', 'Early_Shipments', 'Canceled_Shipments', 'Average_Delay_Gap', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Regional_Delay_Index']

In [77]:
# ==========================================
# DAY 6 - STEP 6
# REGIONAL VISUALIZATION DATA
# ==========================================

regional_viz = regional_analysis[
    [
        "Order Region",
        "Total_Shipments",
        "Delayed_Shipments",
        "On_Time_Shipments",
        "Early_Shipments",
        "Canceled_Shipments",
        "Average_Delay_Gap",
        "Delay_Rate_%",
        "On_Time_Rate_%",
        "Regional_Delay_Index"
    ]
].copy()

# Sort by delay rate
regional_viz = regional_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("REGIONAL VISUALIZATION DATA")
print("==========================================")

display(regional_viz.head(10))

==========================================
REGIONAL VISUALIZATION DATA
==========================================

,Order Region,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Delay_Rate_%,On_Time_Rate_%,Regional_Delay_Index
0,Central Africa,1677,972,290,354,61,0.639833,60.148515,17.945545,60.148515
1,Western Europe,27109,15140,4589,6138,1242,0.597403,58.530174,17.740751,58.530174
2,South of USA,4045,2256,672,927,190,0.579975,58.521401,17.431907,58.521401
3,South Asia,7731,4350,1340,1765,276,0.597465,58.350101,17.974514,58.350101
4,East Africa,1852,1036,346,399,71,0.570734,58.169568,19.427288,58.169568
5,East of USA,6915,3849,1208,1560,298,0.584816,58.168354,18.256007,58.168354
6,Southeast Asia,9539,5297,1631,2208,403,0.558235,57.979422,17.852452,57.979422
7,West Asia,6009,3322,1114,1310,263,0.569479,57.814132,19.387400,57.814132
8,Eastern Europe,3920,2182,724,879,135,0.579847,57.648613,19.128137,57.648613
9,US Center,5887,3252,1174,1227,234,0.587226,57.526977,20.767734,57.526977

In [78]:
"Regional_Delay_Index"

'Regional_Delay_Index'

In [79]:
# ==========================================
# DAY 6 - STEP 7
# MARKET VISUALIZATION DATA
# ==========================================

market_viz = market_analysis[
    [
        "Market",
        "Total_Shipments",
        "Delayed",
        "On-Time",
        "Early",
        "Canceled",
        "Avg_Gap",
        "Delay_Rate_%",
        "On-Time_Rate_%",
        "Cancellation_Rate_%"
    ]
].copy()

# Sort by delay rate
market_viz = market_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("MARKET VISUALIZATION DATA")
print("==========================================")

display(market_viz)

KeyError: "['Delayed', 'On-Time', 'Early', 'Canceled', 'Avg_Gap', 'On-Time_Rate_%'] not in index"

In [80]:
print("Market Analysis columns:")
print(market_analysis.columns.tolist())

Market Analysis columns:
['Market', 'Total_Shipments', 'Delayed_Shipments', 'On_Time_Shipments', 'Early_Shipments', 'Canceled_Shipments', 'Average_Delay_Gap', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Cancellation_Rate_%', 'Market_Delay_Index']

In [81]:
# ==========================================
# DAY 6 - STEP 7
# MARKET VISUALIZATION DATA
# ==========================================

market_viz = market_analysis[
    [
        "Market",
        "Total_Shipments",
        "Delayed_Shipments",
        "On_Time_Shipments",
        "Early_Shipments",
        "Canceled_Shipments",
        "Average_Delay_Gap",
        "Delay_Rate_%",
        "On_Time_Rate_%",
        "Cancellation_Rate_%",
        "Market_Delay_Index"
    ]
].copy()

# Sort by delay rate
market_viz = market_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("MARKET VISUALIZATION DATA")
print("==========================================")

display(market_viz)

==========================================
MARKET VISUALIZATION DATA
==========================================

,Market,Total_Shipments,Delayed_Shipments,On_Time_Shipments,Early_Shipments,Canceled_Shipments,Average_Delay_Gap,Delay_Rate_%,On_Time_Rate_%,Cancellation_Rate_%,Market_Delay_Index
0,Europe,50252,27743,8743,11604,2162,0.570843,57.689748,18.180495,4.302316,57.689748
1,USCA,25799,14138,4658,5831,1172,0.568859,57.408535,18.914200,4.542812,57.408535
2,Pacific Asia,41260,22712,7400,9473,1675,0.569365,57.375268,18.693950,4.059622,57.375268
3,LATAM,51594,28044,9226,12039,2285,0.557836,56.873999,18.710580,4.428810,56.873999
4,Africa,11614,6340,2169,2645,460,0.560014,56.840595,19.445939,3.960737,56.840595

In [82]:
print("Customer Segment Analysis columns:")
print(customer_segment_analysis.columns.tolist())

Customer Segment Analysis columns:

NameError: name 'customer_segment_analysis' is not defined

In [83]:
# Check DataFrame variables currently available

dataframes = {
    name: obj.shape
    for name, obj in globals().items()
    if isinstance(obj, pd.DataFrame)
}

print("Available DataFrames:")
for name, shape in dataframes.items():
    print(f"{name}: {shape}")

Available DataFrames:
_3: (180519, 40)
df: (180519, 42)
numeric_summary: (21, 3)
df_check: (180519, 40)
validation_table: (4, 4)
risk_vs_performance: (2, 4)
risk_vs_status: (2, 4)
analysis_df: (180519, 42)
shipping_mode_analysis: (4, 9)
shipping_mode_delay: (4, 4)
shipping_efficiency: (4, 11)
regional_analysis: (23, 11)
canada_check: (959, 42)
market_analysis: (5, 12)
market_mode_analysis: (20, 12)
region_mode_analysis: (92, 12)
top_risks: (10, 12)
top_performers: (10, 12)
segment_analysis: (3, 11)
segment_mode_analysis: (12, 13)
delay_comparison: (4, 7)
risk_by_segment: (3, 5)
regional_risk: (23, 7)
regional_priority: (23, 6)
risk_concentration: (23, 6)
kpi_summary: (12, 2)
shipping_mode_deep_dive: (4, 14)
region_mode_severity: (91, 13)
status_mode: (4, 10)
delay_severity: (4, 5)
category_analysis: (50, 11)
category_delay_avg: (50, 2)
department_analysis: (11, 11)
department_delay_avg: (11, 2)
business_impact: (4, 12)
risk_driver_summary: (5, 8)
delayed_only: (98977, 42)
delivery_performance_viz: (4, 3)
delay_gap_viz: (4, 4)
shipping_mode_viz: (4, 7)
regional_viz: (23, 10)
market_viz: (5, 11)

In [84]:
# ==========================================
# DAY 6 - STEP 8
# CUSTOMER SEGMENT VISUALIZATION DATA
# ==========================================

segment_viz = segment_analysis[
    [
        "Customer Segment",
        "Total_Shipments",
        "Delayed",
        "On_Time",
        "Early",
        "Canceled",
        "Avg_Delay_Gap",
        "Delay_Rate_%",
        "On_Time_Rate_%",
        "Cancellation_Rate_%",
        "Avg_Delay_When_Delayed"
    ]
].copy()

# Sort by delay rate
segment_viz = segment_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("CUSTOMER SEGMENT VISUALIZATION DATA")
print("==========================================")

display(segment_viz)

KeyError: "['Total_Shipments', 'Avg_Delay_When_Delayed'] not in index"

In [85]:
print("Segment Analysis columns:")
print(segment_analysis.columns.tolist())

Segment Analysis columns:
['Customer Segment', 'Total', 'Delayed', 'On_Time', 'Early', 'Canceled', 'Avg_Delay_Gap', 'Non_Canceled', 'Delay_Rate_%', 'On_Time_Rate_%', 'Cancellation_Rate_%']

In [86]:
# ==========================================
# DAY 6 - STEP 8
# CUSTOMER SEGMENT VISUALIZATION DATA
# ==========================================

segment_viz = segment_analysis[
    [
        "Customer Segment",
        "Total",
        "Delayed",
        "On_Time",
        "Early",
        "Canceled",
        "Avg_Delay_Gap",
        "Delay_Rate_%",
        "On_Time_Rate_%",
        "Cancellation_Rate_%"
    ]
].copy()

# Rename Total for consistency in visualization
segment_viz = segment_viz.rename(
    columns={
        "Total": "Total_Shipments"
    }
)

# Sort by delay rate
segment_viz = segment_viz.sort_values(
    "Delay_Rate_%",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("CUSTOMER SEGMENT VISUALIZATION DATA")
print("==========================================")

display(segment_viz)

==========================================
CUSTOMER SEGMENT VISUALIZATION DATA
==========================================

,Customer Segment,Total_Shipments,Delayed,On_Time,Early,Canceled,Avg_Delay_Gap,Delay_Rate_%,On_Time_Rate_%,Cancellation_Rate_%
0,Home Office,32226,17747,5722,7348,1409,0.58,57.59,18.57,4.37
1,Consumer,93504,51248,16784,21388,4084,0.56,57.31,18.77,4.37
2,Corporate,54789,29982,9690,12856,2261,0.56,57.08,18.45,4.13

In [87]:
# ==========================================
# DAY 6 - STEP 9
# DELAY SEVERITY VISUALIZATION DATA
# ==========================================

delay_severity_viz = delay_gap_viz[
    [
        "Delay_Gap_Days",
        "Delayed_Shipments",
        "Share_of_Delayed_%",
        "Severity"
    ]
].copy()

# Sort by delay days
delay_severity_viz = delay_severity_viz.sort_values(
    "Delay_Gap_Days"
).reset_index(drop=True)

print("==========================================")
print("DELAY SEVERITY VISUALIZATION DATA")
print("==========================================")

display(delay_severity_viz)

==========================================
DELAY SEVERITY VISUALIZATION DATA
==========================================

   Delay_Gap_Days  Delayed_Shipments  Share_of_Delayed_%        Severity
0               1              60647               58.65     Minor Delay
1               2              28718               27.77  Moderate Delay
2               3               7052                6.82    Severe Delay
3               4               6983                6.75    Severe Delay

In [88]:
print("Business Impact columns:")
print(business_impact.columns.tolist())

Business Impact columns:
['Delivery Performance', 'Shipments', 'Total_Sales', 'Avg_Sales', 'Total_Profit', 'Avg_Profit', 'Avg_Order_Value', 'Avg_Quantity', 'Avg_Discount_Rate', 'Avg_Benefit_Per_Order', 'Shipment_Share_%', 'Sales_Share_%']

In [89]:
# ==========================================
# DAY 6 - STEP 10
# BUSINESS IMPACT VISUALIZATION DATA
# ==========================================

business_viz = business_impact[
    [
        "Delivery Performance",
        "Shipments",
        "Total_Sales",
        "Avg_Sales",
        "Total_Profit",
        "Avg_Profit",
        "Avg_Order_Value",
        "Avg_Quantity",
        "Shipment_Share_%",
        "Sales_Share_%"
    ]
].copy()

# Sort by shipment volume
business_viz = business_viz.sort_values(
    "Shipments",
    ascending=False
).reset_index(drop=True)

print("==========================================")
print("BUSINESS IMPACT VISUALIZATION DATA")
print("==========================================")

display(business_viz)

==========================================
BUSINESS IMPACT VISUALIZATION DATA
==========================================

,Delivery Performance,Shipments,Total_Sales,Avg_Sales,Total_Profit,Avg_Profit,Avg_Order_Value,Avg_Quantity,Shipment_Share_%,Sales_Share_%
0,Delayed,98977,20126394.88,203.34,2140051.68,21.62,182.69,2.13,54.83,54.71
1,Early,41592,8518007.73,204.80,935225.28,22.49,184.08,2.13,23.04,23.16
2,On-Time,32196,6570026.37,204.06,731143.67,22.71,183.43,2.12,17.84,17.86
3,Canceled,7754,1570305.33,202.52,160482.34,20.70,181.81,2.13,4.30,4.27

In [90]:
# ==========================================
# DAY 6 - FINAL STEP
# SAVE VISUALIZATION DATASETS
# ==========================================

viz_path = r"D:\APL_Logistics_Project\04_Analysis"

delivery_performance_viz.to_csv(
    rf"{viz_path}\Viz_Delivery_Performance.csv",
    index=False,
    encoding="utf-8-sig"
)

delay_gap_viz.to_csv(
    rf"{viz_path}\Viz_Delay_Gap_Distribution.csv",
    index=False,
    encoding="utf-8-sig"
)

shipping_mode_viz.to_csv(
    rf"{viz_path}\Viz_Shipping_Mode.csv",
    index=False,
    encoding="utf-8-sig"
)

regional_viz.to_csv(
    rf"{viz_path}\Viz_Regional_Performance.csv",
    index=False,
    encoding="utf-8-sig"
)

market_viz.to_csv(
    rf"{viz_path}\Viz_Market_Performance.csv",
    index=False,
    encoding="utf-8-sig"
)

segment_viz.to_csv(
    rf"{viz_path}\Viz_Customer_Segment.csv",
    index=False,
    encoding="utf-8-sig"
)

delay_severity_viz.to_csv(
    rf"{viz_path}\Viz_Delay_Severity.csv",
    index=False,
    encoding="utf-8-sig"
)

business_viz.to_csv(
    rf"{viz_path}\Viz_Business_Impact.csv",
    index=False,
    encoding="utf-8-sig"
)

print("==========================================")
print("DAY 6 VISUALIZATION FILES SAVED")
print("==========================================")

print("✓ Viz_Delivery_Performance.csv")
print("✓ Viz_Delay_Gap_Distribution.csv")
print("✓ Viz_Shipping_Mode.csv")
print("✓ Viz_Regional_Performance.csv")
print("✓ Viz_Market_Performance.csv")
print("✓ Viz_Customer_Segment.csv")
print("✓ Viz_Delay_Severity.csv")
print("✓ Viz_Business_Impact.csv")

print("\nAll Day 6 visualization datasets saved successfully.")

==========================================
DAY 6 VISUALIZATION FILES SAVED
==========================================
✓ Viz_Delivery_Performance.csv
✓ Viz_Delay_Gap_Distribution.csv
✓ Viz_Shipping_Mode.csv
✓ Viz_Regional_Performance.csv
✓ Viz_Market_Performance.csv
✓ Viz_Customer_Segment.csv
✓ Viz_Delay_Severity.csv
✓ Viz_Business_Impact.csv

All Day 6 visualization datasets saved successfully.